In [2]:
!node --version
!npm --version

v20.19.0
10.8.2

In [6]:
from getpass import getpass

twitter_auth_token = getpass(
    "Masukkan token autentikasi X: "
)

Masukkan token autentikasi X: ··········

In [8]:
print("Token sudah dimasukkan:", bool(twitter_auth_token))

Token sudah dimasukkan: True

In [9]:
!node --version
!npm --version

v20.19.0
10.8.2

In [17]:
import subprocess
from pathlib import Path

query = '"10.10" since:2026-09-12 until:2026-10-13 lang:id'
filename = "uji_promo_1010.csv"

command = [
    "npx", "-y", "tweet-harvest@2.6.1",
    "-o", filename,
    "-s", query,
    "--tab", "LATEST",
    "-l", "10",
    "--token", twitter_auth_token
]

result = subprocess.run(command, text=True)

print("Kode proses:", result.returncode)
print("Perintah scraping selesai.")

Kode proses: 1
Perintah scraping selesai.

In [18]:
from pathlib import Path

for path in Path(".").rglob("uji_promo_1010.csv"):
    print("File ditemukan:", path)

In [19]:
from pathlib import Path

print("Folder kerja saat ini:", Path.cwd())
print("\nFile CSV yang ditemukan:")

csv_files = list(Path(".").rglob("*.csv"))

if csv_files:
    for file in csv_files:
        print("-", file)
else:
    print("Belum ada file CSV ditemukan.")

Folder kerja saat ini: /content

File CSV yang ditemukan:
- sample_data/mnist_train_small.csv
- sample_data/mnist_test.csv
- sample_data/california_housing_train.csv
- sample_data/california_housing_test.csv

In [22]:
import subprocess
from pathlib import Path

query = '"10.10" since:2026-09-12 until:2026-10-13 lang:id'
filename = "uji_promo_1010.csv"

command = [
    "npx", "-y", "tweet-harvest@2.6.1",
    "-o", filename,
    "-s", query,
    "--tab", "LATEST",
    "-l", "10",
    "--token", twitter_auth_token
]

print("Memulai scraping data promo 10.10...")
result = subprocess.run(
    command,
    text=True,
    capture_output=True
)

print("\nKode proses:", result.returncode)
print("\nPesan keluaran:")
print(result.stdout)

print("\nPesan error:")
print(result.stderr)

print("\nPemeriksaan file:")
for file in Path("/content").rglob(filename):
    print("File ditemukan:", file)

Memulai scraping data promo 10.10...

Kode proses: 1

Pesan keluaran:
Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...



Pesan error:
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --no-default-browser-check --disable-dev-shm-usage --disable-edgeupdater --disable-features=AvoidUnnecessaryBeforeUnloadCheckSync,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,BlockOriginHeaderModificationOnRedirect,Translate,AutoDeElevate,OptimizationHints,NetworkTimeServiceQuerying,AimEnabled,msForceBrowserSignIn,msEdgeUpdateLaunchServicesPreferredVersion --enable-features=CDPScreenshotNewSurface --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-updater-scheduler --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --disable-infobars --disable-search-engine-choice-screen --disable-sync --enable-unsafe-swiftshader --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=/tmp/playwright_chromiumdev_profile-LF3S7P --remote-debugging-pipe --no-startup-window
<launched> pid=14736
[pid=14736][err] /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory
Call log:
  - <launching> /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --no-default-browser-check --disable-dev-shm-usage --disable-edgeupdater --disable-features=AvoidUnnecessaryBeforeUnloadCheckSync,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,BlockOriginHeaderModificationOnRedirect,Translate,AutoDeElevate,OptimizationHints,NetworkTimeServiceQuerying,AimEnabled,msForceBrowserSignIn,msEdgeUpdateLaunchServicesPreferredVersion --enable-features=CDPScreenshotNewSurface --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-updater-scheduler --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --disable-infobars --disable-search-engine-choice-screen --disable-sync --enable-unsafe-swiftshader --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=/tmp/playwright_chromiumdev_profile-LF3S7P --remote-debugging-pipe --no-startup-window
  - <launched> pid=14736
  - [pid=14736][err] /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory
  - [pid=14736] <gracefully close start>
  - [pid=14736] <kill>
  - [pid=14736] <will force kill>
  - [pid=14736] exception while trying to kill process: Error: kill ESRCH
  - [pid=14736] <process did exit: exitCode=127, signal=null>
  - [pid=14736] starting temporary directories cleanup
  - [pid=14736] finished temporary directories cleanup
  - [pid=14736] <gracefully close end>

    at Proxy.launch (/root/.npm/_npx/d28e8c2154917da4/node_modules/playwright-extra/dist/index.cjs.js:686:54)
    at async crawl (/root/.npm/_npx/d28e8c2154917da4/node_modules/tweet-harvest/dist/bin.js:254:19) {
  log: [
    '  - <launching> /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --no-default-browser-check --disable-dev-shm-usage --disable-edgeupdater --disable-features=AvoidUnnecessaryBeforeUnloadCheckSync,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,BlockOriginHeaderModificationOnRedirect,Translate,AutoDeElevate,OptimizationHints,NetworkTimeServiceQuerying,AimEnabled,msForceBrowserSignIn,msEdgeUpdateLaunchServicesPreferredVersion --enable-features=CDPScreenshotNewSurface --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-updater-scheduler --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --disable-infobars --disable-search-engine-choice-screen --disable-sync --enable-unsafe-swiftshader --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=/tmp/playwright_chromiumdev_profile-LF3S7P --remote-debugging-pipe --no-startup-window',
    '  - <launched> pid=14736',
    '  - [pid=14736][err] /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory',
    '  - [pid=14736] <gracefully close start>',
    '  - [pid=14736] <kill>',
    '  - [pid=14736] <will force kill>',
    '  - [pid=14736] exception while trying to kill process: Error: kill ESRCH',
    '  - [pid=14736] <process did exit: exitCode=127, signal=null>',
    '  - [pid=14736] starting temporary directories cleanup',
    '  - [pid=14736] finished temporary directories cleanup',
    '  - [pid=14736] <gracefully close end>'
  ]
}

Node.js v20.19.0


Pemeriksaan file:

In [21]:
!apt-get update -qq
!apt-get install -y -qq libatk1.0-0 libatk-bridge2.0-0

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package at-spi2-common.
(Reading database ... 122815 files and directories currently installed.)
Preparing to unpack .../0-at-spi2-common_2.52.0-1build1_all.deb ...
Unpacking at-spi2-common (2.52.0-1build1) ...
Selecting previously unselected package libatspi2.0-0t64:amd64.
Preparing to unpack .../1-libatspi2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../2-libxtst6_2%3a1.2.3-1.1build1_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1.1build1) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../3-session-migration_0.3.9build1_amd64.deb ...
Unpacking session-migration (0.3.9build1) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../4-gsettings-desktop-schemas_46.1-0ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (46.1-0ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../5-at-spi2-core_2.52.0-1build1_amd64.deb ...
Unpacking at-spi2-core (2.52.0-1build1) ...
Selecting previously unselected package libatk1.0-0t64:amd64.
Preparing to unpack .../6-libatk1.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libatk-bridge2.0-0t64:amd64.
Preparing to unpack .../7-libatk-bridge2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up session-migration (0.3.9build1) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1.1build1) ...
Setting up libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up at-spi2-common (2.52.0-1build1) ...
Setting up gsettings-desktop-schemas (46.1-0ubuntu1) ...
Setting up libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Setting up libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libglib2.0-0t64:amd64 (2.80.0-6ubuntu3.9) ...
Setting up at-spi2-core (2.52.0-1build1) ...

In [24]:
import subprocess
from pathlib import Path

query = '"10.10" since:2026-09-12 until:2026-10-13 lang:id'
filename = "uji_promo_1010.csv"

command = [
    "npx", "-y", "tweet-harvest@2.6.1",
    "-o", filename,
    "-s", query,
    "--tab", "LATEST",
    "-l", "10",
    "--token", twitter_auth_token
]

print("Memulai scraping data promo 10.10...")
result = subprocess.run(
    command,
    text=True,
    capture_output=True
)

print("\nKode proses:", result.returncode)
print("\nPesan keluaran:")
print(result.stdout)

print("\nPesan error:")
print(result.stderr)

print("\nPemeriksaan file:")
for file in Path("/content").rglob(filename):
    print("File ditemukan:", file)

Memulai scraping data promo 10.10...

Kode proses: 1

Pesan keluaran:
Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...



Pesan error:
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --no-default-browser-check --disable-dev-shm-usage --disable-edgeupdater --disable-features=AvoidUnnecessaryBeforeUnloadCheckSync,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,BlockOriginHeaderModificationOnRedirect,Translate,AutoDeElevate,OptimizationHints,NetworkTimeServiceQuerying,AimEnabled,msForceBrowserSignIn,msEdgeUpdateLaunchServicesPreferredVersion --enable-features=CDPScreenshotNewSurface --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-updater-scheduler --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --disable-infobars --disable-search-engine-choice-screen --disable-sync --enable-unsafe-swiftshader --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=/tmp/playwright_chromiumdev_profile-Yb1sWF --remote-debugging-pipe --no-startup-window
<launched> pid=14992
[pid=14992][err] /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory
Call log:
  - <launching> /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --no-default-browser-check --disable-dev-shm-usage --disable-edgeupdater --disable-features=AvoidUnnecessaryBeforeUnloadCheckSync,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,BlockOriginHeaderModificationOnRedirect,Translate,AutoDeElevate,OptimizationHints,NetworkTimeServiceQuerying,AimEnabled,msForceBrowserSignIn,msEdgeUpdateLaunchServicesPreferredVersion --enable-features=CDPScreenshotNewSurface --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-updater-scheduler --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --disable-infobars --disable-search-engine-choice-screen --disable-sync --enable-unsafe-swiftshader --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=/tmp/playwright_chromiumdev_profile-Yb1sWF --remote-debugging-pipe --no-startup-window
  - <launched> pid=14992
  - [pid=14992][err] /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory
  - [pid=14992] <gracefully close start>
  - [pid=14992] <kill>
  - [pid=14992] <will force kill>
  - [pid=14992] exception while trying to kill process: Error: kill ESRCH
  - [pid=14992] <process did exit: exitCode=127, signal=null>
  - [pid=14992] starting temporary directories cleanup
  - [pid=14992] finished temporary directories cleanup
  - [pid=14992] <gracefully close end>

    at Proxy.launch (/root/.npm/_npx/d28e8c2154917da4/node_modules/playwright-extra/dist/index.cjs.js:686:54)
    at async crawl (/root/.npm/_npx/d28e8c2154917da4/node_modules/tweet-harvest/dist/bin.js:254:19) {
  log: [
    '  - <launching> /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --no-default-browser-check --disable-dev-shm-usage --disable-edgeupdater --disable-features=AvoidUnnecessaryBeforeUnloadCheckSync,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,BlockOriginHeaderModificationOnRedirect,Translate,AutoDeElevate,OptimizationHints,NetworkTimeServiceQuerying,AimEnabled,msForceBrowserSignIn,msEdgeUpdateLaunchServicesPreferredVersion --enable-features=CDPScreenshotNewSurface --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-updater-scheduler --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --disable-infobars --disable-search-engine-choice-screen --disable-sync --enable-unsafe-swiftshader --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=/tmp/playwright_chromiumdev_profile-Yb1sWF --remote-debugging-pipe --no-startup-window',
    '  - <launched> pid=14992',
    '  - [pid=14992][err] /root/.cache/ms-playwright/chromium_headless_shell-1248/chrome-headless-shell-linux64/chrome-headless-shell: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory',
    '  - [pid=14992] <gracefully close start>',
    '  - [pid=14992] <kill>',
    '  - [pid=14992] <will force kill>',
    '  - [pid=14992] exception while trying to kill process: Error: kill ESRCH',
    '  - [pid=14992] <process did exit: exitCode=127, signal=null>',
    '  - [pid=14992] starting temporary directories cleanup',
    '  - [pid=14992] finished temporary directories cleanup',
    '  - [pid=14992] <gracefully close end>'
  ]
}

Node.js v20.19.0


Pemeriksaan file:

In [25]:
from pathlib import Path

files = list(Path("/content").rglob("uji_promo_1010.csv"))

if files:
    for file in files:
        print("CSV ditemukan:", file)
else:
    print("CSV belum terbentuk.")

CSV belum terbentuk.

In [27]:
import subprocess

result = subprocess.run(
    ["bash", "-lc", "ldconfig -p | grep libatk-1.0.so.0"],
    capture_output=True,
    text=True
)

print(result.stdout or "Library libatk belum ditemukan.")

	libatk-1.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libatk-1.0.so.0

In [28]:
!npx -y playwright install-deps chromium

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦Installing dependencies...
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/ InRelease
Hit:3 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:4 https://r2u.stat.illinois.edu/ubuntu noble InRelease
Hit:5 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:6 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libasound2t64 is already the newest version (1.2.11-1ubuntu0.3).
libasound2t64 set to manually installed.
libatk-bridge2.0-0t64 is already the newest version (2.52.0-1build1).
libatk1.0-0t64 is already the newest version (2.52.0-1build1).
libatspi2.0-0t64 is already the newest version (2.52.0-1build1).
libatspi2.0-0t64 set to manually installed.
libcairo2 is already the newest version (1.18.0-3build1).
libcairo2 set to manually installed.
libcups2t64 is already the newest version (2.4.7-1.2ubuntu7.14).
libcups2t64 set to manually installed.
libdbus-1-3 is already the newest version (1.14.10-4ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.125-1ubuntu0.1~24.04.2).
libdrm2 set to manually installed.
libglib2.0-0t64 is already the newest version (2.80.0-6ubuntu3.9).
libglib2.0-0t64 set to manually installed.
libnspr4 is already the newest version (2:4.35-1.1build1).
libnspr4 set to manually installed.
libnss3 is already the newest version (2:3.98-1ubuntu0.2).
libnss3 set to manually installed.
libpango-1.0-0 is already the newest version (1.52.1+ds-1build1).
libpango-1.0-0 set to manually installed.
libxcb1 is already the newest version (1.15-1ubuntu2).
libxcb1 set to manually installed.
libxdamage1 is already the newest version (1:1.1.6-1build1).
libxdamage1 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build2).
libxfixes3 is already the newest version (1:6.0.0-2build1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.6.0-1build1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-2build1).
libxrandr2 set to manually installed.
xvfb is already the newest version (2:21.1.12-1ubuntu1.8).
libfontconfig1 is already the newest version (2.15.0-1.1ubuntu2).
fonts-liberation is already the newest version (1:2.1.5-3).
The following package was automatically installed and is no longer required:
  libwayland-server0
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  libegl-mesa0 libfreetype-dev libgl1-mesa-dri libglx-mesa0 libx11-data
  libx11-dev libx11-xcb1 mesa-libgallium xfonts-encodings xfonts-utils
Suggested packages:
  freetype2-doc libx11-doc
Recommended packages:
  fonts-ipafont-mincho fonts-tlwg-loma
The following NEW packages will be installed:
  fonts-freefont-ttf fonts-ipafont-gothic fonts-noto-color-emoji
  fonts-tlwg-loma-otf fonts-unifont fonts-wqy-zenhei libxcomposite1
  xfonts-cyrillic xfonts-encodings xfonts-scalable xfonts-utils
The following packages will be upgraded:
  libegl-mesa0 libfreetype-dev libfreetype6 libgbm1 libgl1-mesa-dri
  libglx-mesa0 libx11-6 libx11-data libx11-dev libx11-xcb1 mesa-libgallium
11 upgraded, 11 newly installed, 0 to remove and 17 not upgraded.
Need to get 44.4 MB of archives.
After this operation, 90.4 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/universe amd64 fonts-ipafont-gothic all 00303-21ubuntu1 [3,513 kB]
Get:2 http://security.ubuntu.com/ubuntu noble-security/main amd64 libx11-dev amd64 2:1.8.7-1ubuntu0.1 [732 kB]
Get:3 http://security.ubuntu.com/ubuntu noble-security/main amd64 libx11-6 amd64 2:1.8.7-1ubuntu0.1 [653 kB]
Get:4 http://security.ubuntu.com/ubuntu noble-security/main amd64 libx11-xcb1 amd64 2:1.8.7-1ubuntu0.1 [7,796 B]
Get:5 http://security.ubuntu.com/ubuntu noble-security/main amd64 libx11-data all 2:1.8.7-1ubuntu0.1 [116 kB]
Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 fonts-freefont-ttf all 20211204+svn4273-2 [5,641 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 fonts-noto-color-emoji all 2.047-0ubuntu0.24.04.1 [9,764 kB]
Get:8 http://archive.ubuntu.com/ubuntu noble/universe amd64 fonts-tlwg-loma-otf all 1:0.7.3-1 [107 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble/universe amd64 fonts-unifont all 1:15.1.01-1build1 [2,993 kB]
Get:10 http://archive.ubuntu.com/ubuntu noble/universe amd64 fonts-wqy-zenhei all 0.9.45-8 [7,472 kB]
Get:11 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgl1-mesa-dri amd64 25.2.8-0ubuntu0.24.04.4 [38.0 kB]
Get:12 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libglx-mesa0 amd64 25.2.8-0ubuntu0.24.04.4 [110 kB]
Get:13 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libegl-mesa0 amd64 25.2.8-0ubuntu0.24.04.4 [117 kB]
Get:14 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgbm1 amd64 25.2.8-0ubuntu0.24.04.4 [34.2 kB]
Get:15 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 mesa-libgallium amd64 25.2.8-0ubuntu0.24.04.4 [10.8 MB]
Get:16 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libfreetype-dev amd64 2.13.2+dfsg-1ubuntu0.2 [574 kB]
Get:17 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libfreetype6 amd64 2.13.2+dfsg-1ubuntu0.2 [403 kB]
Get:18 http://archive.ubuntu.com/ubuntu noble/main amd64 libxcomposite1 amd64 1:0.4.5-1build3 [6,320 B]
Get:19 http://archive.ubuntu.com/ubuntu noble/main amd64 xfonts-encodings all 1:1.0.5-0ubuntu2 [578 kB]
Get:20 http://archive.ubuntu.com/ubuntu noble/main amd64 xfonts-utils amd64 1:7.7+6build3 [94.4 kB]
Get:21 http://archive.ubuntu.com/ubuntu noble/universe amd64 xfonts-cyrillic all 1:1.0.5+nmu1 [384 kB]
Get:22 http://archive.ubuntu.com/ubuntu noble/main amd64 xfonts-scalable all 1:1.0.3-1.3 [304 kB]
Fetched 44.4 MB in 3s (17.1 MB/s)
Selecting previously unselected package fonts-ipafont-gothic.
(Reading database ... 122919 files and directories currently installed.)
Preparing to unpack .../00-fonts-ipafont-gothic_00303-21ubuntu1_all.deb ...
Unpacking fonts-ipafont-gothic (00303-21ubuntu1) ...
Preparing to unpack .../01-libx11-dev_2%3a1.8.7-1ubuntu0.1_amd64.deb ...
Unpacking libx11-dev:amd64 (2:1.8.7-1ubuntu0.1) over (2:1.8.7-1build1) ...
Preparing to unpack .../02-libx11-6_2%3a1.8.7-1ubuntu0.1_amd64.deb ...
Unpacking libx11-6:amd64 (2:1.8.7-1ubuntu0.1) over (2:1.8.7-1build1) ...
Preparing to unpack .../03-libx11-xcb1_2%3a1.8.7-1ubuntu0.1_amd64.deb ...
Unpacking libx11-xcb1:amd64 (2:1.8.7-1ubuntu0.1) over (2:1.8.7-1build1) ...
Preparing to unpack .../04-libx11-data_2%3a1.8.7-1ubuntu0.1_all.deb ...
Unpacking libx11-data (2:1.8.7-1ubuntu0.1) over (2:1.8.7-1build1) ...
Selecting previously unselected package fonts-freefont-ttf.
Preparing to unpack .../05-fonts-freefont-ttf_20211204+svn4273-2_all.deb ...
Unpacking fonts-freefont-ttf (20211204+svn4273-2) ...
Selecting previously unselected package fonts-noto-color-emoji.
Preparing to unpack .../06-fonts-noto-color-emoji_2.047-0ubuntu0.24.04.1_all.deb ...
Unpacking fonts-noto-color-emoji (2.047-0ubuntu0.24.04.1) ...
Selecting previously unselected package fonts-tlwg-loma-otf.
Preparing to unpack .../07-fonts-tlwg-loma-otf_1%3a0.7.3-1_all.deb ...
Unpacking fonts-tlwg-loma-otf (1:0.7.3-1) ...
Selecting previously unselected package fonts-unifont.
Preparing to unpack .../08-fonts-unifont_1%3a15.1.01-1build1_all.deb ...
Unpacking fonts-unifont (1:15.1.01-1build1) ...
Selecting previously unselected package fonts-wqy-zenhei.
Preparing to unpack .../09-fonts-wqy-zenhei_0.9.45-8_all.deb ...
Unpacking fonts-wqy-zenhei (0.9.45-8) ...
Preparing to unpack .../10-libgl1-mesa-dri_25.2.8-0ubuntu0.24.04.4_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (25.2.8-0ubuntu0.24.04.4) over (25.2.8-0ubuntu0.24.04.3) ...
Preparing to unpack .../11-libglx-mesa0_25.2.8-0ubuntu0.24.04.4_amd64.deb ...
Unpacking libglx-mesa0:amd64 (25.2.8-0ubuntu0.24.04.4) over (25.2.8-0ubuntu0.24.04.3) ...
Preparing to unpack .../12-libegl-mesa0_25.2.8-0ubuntu0.24.04.4_amd64.deb ...
Unpacking libegl-mesa0:amd64 (25.2.8-0ubuntu0.24.04.4) over (25.2.8-0ubuntu0.24.04.3) ...
Preparing to unpack .../13-libgbm1_25.2.8-0ubuntu0.24.04.4_amd64.deb ...
Unpacking libgbm1:amd64 (25.2.8-0ubuntu0.24.04.4) over (25.2.8-0ubuntu0.24.04.3) ...
Preparing to unpack .../14-mesa-libgallium_25.2.8-0ubuntu0.24.04.4_amd64.deb ...
Unpacking mesa-libgallium:amd64 (25.2.8-0ubuntu0.24.04.4) over (25.2.8-0ubuntu0.24.04.3) ...
Preparing to unpack .../15-libfreetype-dev_2.13.2+dfsg-1ubuntu0.2_amd64.deb ...
Unpacking libfreetype-dev:amd64 (2.13.2+dfsg-1ubuntu0.2) over (2.13.2+dfsg-1ubuntu0.1) ...
Preparing to unpack .../16-libfreetype6_2.13.2+dfsg-1ubuntu0.2_amd64.deb ...
Unpacking libfreetype6:amd64 (2.13.2+dfsg-1ubuntu0.2) over (2.13.2+dfsg-1ubuntu0.1) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../17-libxcomposite1_1%3a0.4.5-1build3_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build3) ...
Selecting previously unselected package xfonts-encodings.
Preparing to unpack .../18-xfonts-encodings_1%3a1.0.5-0ubuntu2_all.deb ...
Unpacking xfonts-encodings (1:1.0.5-0ubuntu2) ...
Selecting previously unselected package xfonts-utils.
Preparing to unpack .../19-xfonts-utils_1%3a7.7+6build3_amd64.deb ...
Unpacking xfonts-utils (1:7.7+6build3) ...
Selecting previously unselected package xfonts-cyrillic.
Preparing to unpack .../20-xfonts-cyrillic_1%3a1.0.5+nmu1_all.deb ...
Unpacking xfonts-cyrillic (1:1.0.5+nmu1) ...
Selecting previously unselected package xfonts-scalable.
Preparing to unpack .../21-xfonts-scalable_1%3a1.0.3-1.3_all.deb ...
Unpacking xfonts-scalable (1:1.0.3-1.3) ...
Setting up fonts-noto-color-emoji (2.047-0ubuntu0.24.04.1) ...
Setting up fonts-wqy-zenhei (0.9.45-8) ...
Setting up fonts-freefont-ttf (20211204+svn4273-2) ...
Setting up fonts-tlwg-loma-otf (1:0.7.3-1) ...
Setting up libfreetype6:amd64 (2.13.2+dfsg-1ubuntu0.2) ...
Setting up libx11-data (2:1.8.7-1ubuntu0.1) ...
Setting up xfonts-encodings (1:1.0.5-0ubuntu2) ...
Setting up fonts-ipafont-gothic (00303-21ubuntu1) ...
update-alternatives: using /usr/share/fonts/opentype/ipafont-gothic/ipag.ttf to provide /usr/share/fonts/truetype/fonts-japanese-gothic.ttf (fonts-japanese-gothic.ttf) in auto mode
Setting up libx11-6:amd64 (2:1.8.7-1ubuntu0.1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build3) ...
Setting up fonts-unifont (1:15.1.01-1build1) ...
Setting up libx11-xcb1:amd64 (2:1.8.7-1ubuntu0.1) ...
Setting up mesa-libgallium:amd64 (25.2.8-0ubuntu0.24.04.4) ...
Setting up libgbm1:amd64 (25.2.8-0ubuntu0.24.04.4) ...
Setting up libgl1-mesa-dri:amd64 (25.2.8-0ubuntu0.24.04.4) ...
Setting up libx11-dev:amd64 (2:1.8.7-1ubuntu0.1) ...
Setting up xfonts-utils (1:7.7+6build3) ...
Setting up libfreetype-dev:amd64 (2.13.2+dfsg-1ubuntu0.2) ...
Setting up libegl-mesa0:amd64 (25.2.8-0ubuntu0.24.04.4) ...
Setting up xfonts-cyrillic (1:1.0.5+nmu1) ...
Setting up xfonts-scalable (1:1.0.3-1.3) ...
Setting up libglx-mesa0:amd64 (25.2.8-0ubuntu0.24.04.4) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for fontconfig (2.15.0-1.1ubuntu2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

⠙

In [29]:
!npx -y playwright install chromium

⠙⠹⠸⠼⠴⠦╔═══════════════════════════════════════════════════════════════════════════════╗
║ WARNING: It looks like you are running 'npx playwright install' without first ║
║ installing your project's dependencies.                                       ║
║                                                                               ║
║ To avoid unexpected behavior, please install your dependencies first, and     ║
║ then run Playwright's install command:                                        ║
║                                                                               ║
║     npm install                                                               ║
║     npx playwright install                                                    ║
║                                                                               ║
║ If your project does not yet depend on Playwright, first install the          ║
║ applicable npm package (most commonly @playwright/test), and                  ║
║ then run Playwright's install command to download the browsers:               ║
║                                                                               ║
║     npm install @playwright/test                                              ║
║     npx playwright install                                                    ║
║                                                                               ║
╚═══════════════════════════════════════════════════════════════════════════════╝
⠙

In [30]:
import subprocess

test = subprocess.run(
    [
        "npx", "-y", "-p", "playwright",
        "-c",
        "node -e \"console.log('Node.js berjalan')\""
    ],
    capture_output=True,
    text=True
)

print("Kode proses:", test.returncode)
print("Output:", test.stdout)
print("Error:", test.stderr[-2000:])

Kode proses: 0
Output: Node.js berjalan

Error:

In [31]:
import subprocess

# Pasang Playwright sementara dan uji Chromium
cmd = [
    "npx", "-y", "-p", "playwright",
    "-c",
    'node -e "const { chromium } = require(\'playwright\'); '
    '(async () => { '
    'const browser = await chromium.launch({headless:true}); '
    'console.log(\'CHROMIUM BERHASIL DIBUKA\'); '
    'await browser.close(); '
    '})().catch(err => { console.error(err); process.exit(1); });"'
]

test = subprocess.run(
    cmd,
    capture_output=True,
    text=True
)

print("Kode proses:", test.returncode)
print("Output:", test.stdout)
print("Error:", test.stderr[-3000:])

Kode proses: 1
Output:
Error: node:internal/modules/cjs/loader:1215
  throw err;
  ^

Error: Cannot find module 'playwright'
Require stack:
- /content/[eval]
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at [eval]:1:22
    at runScriptInThisContext (node:internal/vm:209:10)
    at node:internal/process/execution:118:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:101:62)
    at evalScript (node:internal/process/execution:133:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/content/[eval]' ]
}

Node.js v20.19.0

In [33]:
%cd /content
!npm install playwright

/content
⠙⠹⠸⠼
up to date, audited 3 packages in 1s
⠼
found 0 vulnerabilities
⠼

In [34]:
!npx playwright install chromium

⠙⠙

In [36]:
%pip install playwright

Collecting playwright
  Downloading playwright-1.63.0-py3-none-manylinux1_x86_64.whl.metadata (3.3 kB)
Collecting pyee<14,>=13 (from playwright)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright)
  Downloading greenlet-3.5.6-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.13/dist-packages (from pyee<14,>=13->playwright) (4.16.0)
Downloading playwright-1.63.0-py3-none-manylinux1_x86_64.whl (48.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 MB 18.1 MB/s eta 0:00:00
Downloading greenlet-3.5.6-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (623 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.8/623.8 kB 29.8 MB/s eta 0:00:00
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: pyee, greenlet, playwright
Successfully installed greenlet-3.5.6 playwright-1.63.0 pyee-13.0.1

In [37]:
import asyncio
from playwright.async_api import async_playwright

async def uji_chromium():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        print("BERHASIL: Chromium dapat dibuka.")
        await browser.close()

await uji_chromium()

Error: BrowserType.launch: Executable doesn't exist at /root/.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

In [38]:
!python -m playwright install chromium

Downloading Chrome for Testing 153.0.8010.12 (playwright chromium v1243) from https://cdn.playwright.dev/builds/cft/153.0.8010.12/linux64/chrome-linux64.zip
186.8 MiB [] 0% 379.5s186.8 MiB [] 0% 37.4s186.8 MiB [] 0% 21.8s186.8 MiB [] 0% 18.8s186.8 MiB [] 0% 16.9s186.8 MiB [] 0% 10.2s186.8 MiB [] 1% 7.9s186.8 MiB [] 1% 6.7s186.8 MiB [] 2% 6.1s186.8 MiB [] 2% 5.5s186.8 MiB [] 3% 5.3s186.8 MiB [] 3% 5.1s186.8 MiB [] 4% 4.9s186.8 MiB [] 4% 4.7s186.8 MiB [] 5% 4.6s186.8 MiB [] 5% 4.5s186.8 MiB [] 6% 4.4s186.8 MiB [] 6% 4.3s186.8 MiB [] 7% 4.7s186.8 MiB [] 7% 4.9s186.8 MiB [] 7% 5.1s186.8 MiB [] 7% 5.0s186.8 MiB [] 8% 4.7s186.8 MiB [] 8% 4.5s186.8 MiB [] 9% 4.2s186.8 MiB [] 10% 4.0s186.8 MiB [] 11% 3.8s186.8 MiB [] 12% 3.7s186.8 MiB [] 12% 3.5s186.8 MiB [] 13% 3.4s186.8 MiB [] 14% 3.4s186.8 MiB [] 15% 3.3s186.8 MiB [] 16% 3.3s186.8 MiB [] 16% 3.2s186.8 MiB [] 17% 3.2s186.8 MiB [] 18% 3.2s186.8 MiB [] 18% 3.1s186.8 MiB [] 19% 3.1s186.8 MiB [] 19% 3.2s186.8 MiB [] 19% 3.3s186.8 MiB [] 20% 3.4s186.8 MiB [] 20% 3.3s186.8 MiB [] 21% 3.3s186.8 MiB [] 21% 3.2s186.8 MiB [] 22% 3.2s186.8 MiB [] 23% 3.1s186.8 MiB [] 24% 3.1s186.8 MiB [] 24% 3.2s186.8 MiB [] 25% 3.1s186.8 MiB [] 26% 3.0s186.8 MiB [] 27% 2.9s186.8 MiB [] 28% 2.9s186.8 MiB [] 28% 2.8s186.8 MiB [] 29% 2.7s186.8 MiB [] 30% 2.7s186.8 MiB [] 31% 2.6s186.8 MiB [] 32% 2.5s186.8 MiB [] 33% 2.4s186.8 MiB [] 34% 2.3s186.8 MiB [] 35% 2.3s186.8 MiB [] 36% 2.2s186.8 MiB [] 37% 2.2s186.8 MiB [] 38% 2.1s186.8 MiB [] 39% 2.0s186.8 MiB [] 40% 2.0s186.8 MiB [] 41% 2.0s186.8 MiB [] 42% 2.0s186.8 MiB [] 43% 1.9s186.8 MiB [] 44% 1.8s186.8 MiB [] 45% 1.8s186.8 MiB [] 46% 1.8s186.8 MiB [] 47% 1.7s186.8 MiB [] 48% 1.7s186.8 MiB [] 49% 1.6s186.8 MiB [] 50% 1.6s186.8 MiB [] 51% 1.5s186.8 MiB [] 52% 1.5s186.8 MiB [] 53% 1.4s186.8 MiB [] 54% 1.4s186.8 MiB [] 55% 1.4s186.8 MiB [] 56% 1.3s186.8 MiB [] 57% 1.3s186.8 MiB [] 58% 1.2s186.8 MiB [] 58% 1.3s186.8 MiB [] 59% 1.2s186.8 MiB [] 60% 1.2s186.8 MiB [] 61% 1.2s186.8 MiB [] 62% 1.1s186.8 MiB [] 63% 1.1s186.8 MiB [] 64% 1.1s186.8 MiB [] 65% 1.0s186.8 MiB [] 66% 1.0s186.8 MiB [] 67% 1.0s186.8 MiB [] 68% 0.9s186.8 MiB [] 68% 1.0s186.8 MiB [] 69% 1.0s186.8 MiB [] 70% 1.0s186.8 MiB [] 70% 0.9s186.8 MiB [] 71% 0.9s186.8 MiB [] 72% 0.9s186.8 MiB [] 73% 0.8s186.8 MiB [] 74% 0.8s186.8 MiB [] 75% 0.8s186.8 MiB [] 76% 0.8s186.8 MiB [] 76% 0.7s186.8 MiB [] 77% 0.7s186.8 MiB [] 78% 0.7s186.8 MiB [] 79% 0.6s186.8 MiB [] 80% 0.6s186.8 MiB [] 81% 0.6s186.8 MiB [] 82% 0.6s186.8 MiB [] 83% 0.5s186.8 MiB [] 84% 0.5s186.8 MiB [] 85% 0.5s186.8 MiB [] 86% 0.4s186.8 MiB [] 87% 0.4s186.8 MiB [] 88% 0.4s186.8 MiB [] 89% 0.3s186.8 MiB [] 90% 0.3s186.8 MiB [] 91% 0.3s186.8 MiB [] 92% 0.2s186.8 MiB [] 93% 0.2s186.8 MiB [] 94% 0.2s186.8 MiB [] 95% 0.2s186.8 MiB [] 95% 0.1s186.8 MiB [] 96% 0.1s186.8 MiB [] 97% 0.1s186.8 MiB [] 98% 0.0s186.8 MiB [] 99% 0.0s186.8 MiB [] 100% 0.0s
Chrome for Testing 153.0.8010.12 (playwright chromium v1243) downloaded to /root/.cache/ms-playwright/chromium-1243
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
2.3 MiB [] 0% 0.0s2.3 MiB [] 7% 0.2s2.3 MiB [] 15% 0.2s2.3 MiB [] 32% 0.1s2.3 MiB [] 58% 0.0s2.3 MiB [] 90% 0.0s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011
Downloading Chrome Headless Shell 153.0.8010.12 (playwright chromium-headless-shell v1243) from https://cdn.playwright.dev/builds/cft/153.0.8010.12/linux64/chrome-headless-shell-linux64.zip
114.3 MiB [] 0% 0.0s114.3 MiB [] 0% 37.1s114.3 MiB [] 0% 23.4s114.3 MiB [] 0% 19.2s114.3 MiB [] 0% 15.8s114.3 MiB [] 0% 13.3s114.3 MiB [] 1% 9.2s114.3 MiB [] 2% 5.5s114.3 MiB [] 3% 4.0s114.3 MiB [] 3% 3.7s114.3 MiB [] 4% 3.4s114.3 MiB [] 5% 3.0s114.3 MiB [] 6% 2.8s114.3 MiB [] 7% 2.7s114.3 MiB [] 8% 2.6s114.3 MiB [] 9% 2.4s114.3 MiB [] 10% 2.4s114.3 MiB [] 10% 2.3s114.3 MiB [] 11% 2.5s114.3 MiB [] 11% 2.6s114.3 MiB [] 11% 2.8s114.3 MiB [] 11% 3.0s114.3 MiB [] 11% 3.1s114.3 MiB [] 12% 2.9s114.3 MiB [] 14% 2.8s114.3 MiB [] 15% 2.6s114.3 MiB [] 16% 2.5s114.3 MiB [] 17% 2.3s114.3 MiB [] 19% 2.2s114.3 MiB [] 20% 2.1s114.3 MiB [] 21% 2.0s114.3 MiB [] 22% 2.0s114.3 MiB [] 23% 2.0s114.3 MiB [] 24% 1.9s114.3 MiB [] 25% 1.9s114.3 MiB [] 26% 1.8s114.3 MiB [] 28% 1.7s114.3 MiB [] 29% 1.6s114.3 MiB [] 31% 1.5s114.3 MiB [] 32% 1.5s114.3 MiB [] 34% 1.4s114.3 MiB [] 35% 1.3s114.3 MiB [] 37% 1.3s114.3 MiB [] 39% 1.2s114.3 MiB [] 39% 1.3s114.3 MiB [] 41% 1.2s114.3 MiB [] 43% 1.2s114.3 MiB [] 45% 1.1s114.3 MiB [] 47% 1.0s114.3 MiB [] 49% 1.0s114.3 MiB [] 51% 0.9s114.3 MiB [] 53% 0.8s114.3 MiB [] 55% 0.8s114.3 MiB [] 57% 0.7s114.3 MiB [] 60% 0.7s114.3 MiB [] 61% 0.6s114.3 MiB [] 64% 0.6s114.3 MiB [] 65% 0.5s114.3 MiB [] 66% 0.5s114.3 MiB [] 66% 0.6s114.3 MiB [] 67% 0.6s114.3 MiB [] 68% 0.5s114.3 MiB [] 70% 0.5s114.3 MiB [] 72% 0.4s114.3 MiB [] 74% 0.4s114.3 MiB [] 77% 0.4s114.3 MiB [] 79% 0.3s114.3 MiB [] 81% 0.3s114.3 MiB [] 83% 0.3s114.3 MiB [] 85% 0.2s114.3 MiB [] 87% 0.2s114.3 MiB [] 89% 0.1s114.3 MiB [] 92% 0.1s114.3 MiB [] 94% 0.1s114.3 MiB [] 95% 0.1s114.3 MiB [] 96% 0.1s114.3 MiB [] 97% 0.0s114.3 MiB [] 98% 0.0s114.3 MiB [] 99% 0.0s114.3 MiB [] 100% 0.0s
Chrome Headless Shell 153.0.8010.12 (playwright chromium-headless-shell v1243) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1243

In [40]:
import subprocess
from pathlib import Path

query = '"10.10" since:2026-09-12 until:2026-10-13 lang:id'
filename = "uji_promo_1010.csv"

command = [
    "npx", "-y", "tweet-harvest@2.6.1",
    "-o", filename,
    "-s", query,
    "--tab", "LATEST",
    "-l", "10",
    "--token", twitter_auth_token
]

result = subprocess.run(
    command,
    capture_output=True,
    text=True
)

print("Kode proses:", result.returncode)
print("Keluaran:")
print(result.stdout)
print("Pesan error:")
print(result.stderr[-3000:])

print("\nPemeriksaan file:")
files = list(Path("/content").rglob(filename))

if files:
    for file in files:
        print("CSV ditemukan:", file)
else:
    print("CSV belum terbentuk.")

Kode proses: 0
Keluaran:
Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: "10.10" since:2026-09-12 until:2026-10-13 lang:id

 (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)No tweets found for the search criteria

Pesan error:


Pemeriksaan file:
CSV belum terbentuk.

In [41]:
import subprocess
from pathlib import Path

query = 'promo 10.10 lang:id since:2026-09-12 until:2026-10-13'
filename = "uji_promo_1010.csv"

command = [
    "npx", "-y", "tweet-harvest@2.6.1",
    "-o", filename,
    "-s", query,
    "--tab", "LATEST",
    "-l", "10",
    "--token", twitter_auth_token
]

result = subprocess.run(
    command,
    capture_output=True,
    text=True
)

print("Kode proses:", result.returncode)
print(result.stdout)
print(result.stderr[-2000:])

files = list(Path("/content").rglob(filename))
print("\nFile ditemukan:")
for file in files:
    print(file)

Kode proses: 0
Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: promo 10.10 lang:id since:2026-09-12 until:2026-10-13

 (2)Created new directory: /content/tweets-data


Your tweets saved to: /content/tweets-data/uji_promo_1010.csv
Total tweets saved: 0

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)No tweets found for the search criteria



File ditemukan:
/content/tweets-data/uji_promo_1010.csv

In [43]:
import subprocess
from pathlib import Path

query = "promo"
filename = "uji_promo_1010_v271.csv"

command = [
    "npx", "-y", "tweet-harvest@2.7.1",
    "-o", filename,
    "-s", query,
    "--tab", "LATEST",
    "-l", "10",
    "--token", twitter_auth_token
]

result = subprocess.run(
    command,
    capture_output=True,
    text=True
)

print("Kode proses:", result.returncode)
print("Keluaran:")
print(result.stdout)
print("\nPesan error:")
print(result.stderr[-2500:])

print("\nFile hasil:")
for file in Path("/content").rglob(filename):
    print(file)

Kode proses: 0
Keluaran:
Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: promo

 (4) (5) (6) (7) (8)

Your tweets saved to: /content/tweets-data/uji_promo_1010_v271.csv
Total tweets saved: 20
Got 20 tweets, done scrolling...


Pesan error:
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
npm warn deprecated @playwright/test@1.41.1: Please update to the latest version of Playwright to test up-to-date browsers.


File hasil:
/content/tweets-data/uji_promo_1010_v271.csv

In [47]:

import subprocess
from pathlib import Path
import pandas as pd

query = "tanggal kembar since:2026-09-12 until:2026-10-13 lang:id"
filename = "dataset_tanggal_kembar.csv"

command = [
    "npx", "-y", "tweet-harvest@2.7.1",
    "-o", filename,
    "-s", query,
    "--tab", "LATEST",
    "-l", "100",
    "--token", twitter_auth_token
]

result = subprocess.run(command, capture_output=True, text=True)

print("Kode proses:", result.returncode)
print(result.stdout)

if result.stderr:
    print("\nPesan tambahan:")
    print(result.stderr[-1000:])

# Periksa file dan hindari membaca CSV kosong
matches = [
    p for p in Path("/content/tweets-data").glob(filename)
    if p.is_file()
]

if matches and matches[0].stat().st_size > 0:
    try:
        df = pd.read_csv(matches[0])
        print("\nJumlah cuitan:", len(df))

        if len(df) > 0:
            display(df[["created_at", "lang", "full_text"]].head(10))
        else:
            print("CSV ada, tetapi tidak berisi cuitan.")
    except pd.errors.EmptyDataError:
        print("CSV kosong karena tidak ada data yang tersimpan.")
else:
    print("Belum ada data yang tersimpan ke CSV.")

Kode proses: 0
Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: tanggal kembar since:2026-09-12 until:2026-10-13 lang:id

 (3)

Your tweets saved to: /content/tweets-data/dataset_tanggal_kembar.csv
Total tweets saved: 0

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)No tweets found for the search criteria

CSV kosong karena tidak ada data yang tersimpan.

In [49]:

import subprocess
from pathlib import Path
import pandas as pd

query = '"promo 10.10"'
filename = "uji_promo_1010_id.csv"

command = [
    "npx", "-y", "tweet-harvest@2.7.1",
    "-o", filename,
    "-s", query,
    "--tab", "LATEST",
    "-l", "50",
    "--token", twitter_auth_token
]

result = subprocess.run(command, capture_output=True, text=True)

print("Kode proses:", result.returncode)
print(result.stdout)

file_hasil = Path("/content/tweets-data") / filename

if file_hasil.exists() and file_hasil.stat().st_size > 0:
    try:
        df_uji = pd.read_csv(file_hasil)
        print("\nJumlah cuitan:", len(df_uji))

        if len(df_uji) > 0:
            print("\nDistribusi bahasa:")
            display(df_uji["lang"].value_counts().to_frame("jumlah"))
            print("\nContoh cuitan:")
            display(df_uji[["created_at", "lang", "full_text"]].head(15))
        else:
            print("CSV kosong.")
    except pd.errors.EmptyDataError:
        print("CSV ditemukan, tetapi tidak memiliki data.")
else:
    print("File CSV tidak ditemukan atau kosong.")

Kode proses: 0
Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3)
Filling in keywords: "promo 10.10"

 (4) (5)

Your tweets saved to: /content/tweets-data/uji_promo_1010_id.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/uji_promo_1010_id.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/uji_promo_1010_id.csv
Total tweets saved: 60
Got 60 tweets, done scrolling...


Jumlah cuitan: 60

Distribusi bahasa:

      jumlah
lang
in        54
en         5
tr         1

Contoh cuitan:

,created_at,lang,full_text
0,2026-10-12T16:18:00.000Z,in,Sewaktu2 suka ada promo 10.10 diskon tagihan l...
1,2026-10-12T16:16:55.000Z,en,A Day in My Life: 😭😱Latest Elementary School K...
2,2026-10-12T15:41:27.000Z,tr,@andychester7_ Promo 10.10 yak 😁
3,2026-10-12T14:41:51.000Z,in,"@nnawinss Yukk kak, by req &lt;3 promo 10.10 d..."
4,2026-10-12T13:43:59.000Z,en,@yaeiiko Replied yaaaa
5,2026-10-12T12:59:33.000Z,in,hari terakhir jajan layout promo 10.10 ‼️ lesg...
6,2026-10-12T12:40:52.000Z,in,"@bercyinta Chibi dibawah kak, promo 10.10"
7,2026-10-12T12:27:06.000Z,in,Plis beli disni akuh huhuhhhu
8,2026-10-12T12:21:51.000Z,in,Lama lama ku pake sendiri ni disney duhh
9,2026-10-12T12:20:56.000Z,in,haloo adakah yang mau disney aku jual rugi kar...
10,2026-10-12T12:20:50.000Z,in,@capybavra GEMESSSS WARNANYA MASUP GTUU
11,2026-10-12T12:05:06.000Z,in,Masih adakah layout req promo 10.10? Mau jajan...
12,2026-10-12T12:04:31.000Z,in,"@polcadaily Hadireeeu, pas bangeet kak ada pro..."
13,2026-10-12T11:06:08.000Z,in,[Last day]\nVoucher Lazada diskon 15% s/d 1jt\...
14,2026-10-12T10:35:44.000Z,in,aduhhh aku udah gatau mau gimana inii

In [50]:

import pandas as pd
from pathlib import Path

file_asal = Path("/content/tweets-data/uji_promo_1010_id.csv")
df = pd.read_csv(file_asal)

print("Jumlah data awal:", len(df))

# Ambil cuitan berbahasa Indonesia
df_id = df[df["lang"] == "in"].copy()

# Hapus teks kosong dan duplikat
df_id = df_id.dropna(subset=["full_text"])
df_id["full_text"] = df_id["full_text"].astype(str).str.strip()
df_id = df_id[df_id["full_text"] != ""]
df_id = df_id.drop_duplicates(subset=["id_str"])

print("Jumlah cuitan bahasa Indonesia:", len(df_id))
print("Jumlah cuitan unik:", df_id["id_str"].nunique())

display(df_id[["created_at", "full_text", "tweet_url"]].head(15))

Jumlah data awal: 60
Jumlah cuitan bahasa Indonesia: 54
Jumlah cuitan unik: 54

,created_at,full_text,tweet_url
0,2026-10-12T16:18:00.000Z,Sewaktu2 suka ada promo 10.10 diskon tagihan l...,https://x.com/etmrva/status/2109679990208119181
3,2026-10-12T14:41:51.000Z,"@nnawinss Yukk kak, by req &lt;3 promo 10.10 d...",https://x.com/anvseongmin/status/2109655795050...
5,2026-10-12T12:59:33.000Z,hari terakhir jajan layout promo 10.10 ‼️ lesg...,https://x.com/iniBleue/status/2109630048118636798
6,2026-10-12T12:40:52.000Z,"@bercyinta Chibi dibawah kak, promo 10.10",https://x.com/chowcocips/status/21096253492273...
7,2026-10-12T12:27:06.000Z,Plis beli disni akuh huhuhhhu,https://x.com/jieabee/status/2109621885180977584
8,2026-10-12T12:21:51.000Z,Lama lama ku pake sendiri ni disney duhh,https://x.com/jieabee/status/2109620561307443559
9,2026-10-12T12:20:56.000Z,haloo adakah yang mau disney aku jual rugi kar...,https://x.com/jieabee/status/2109620331606593850
10,2026-10-12T12:20:50.000Z,@capybavra GEMESSSS WARNANYA MASUP GTUU,https://x.com/artbyloOomissy/status/2109620304...
11,2026-10-12T12:05:06.000Z,Masih adakah layout req promo 10.10? Mau jajan...,https://x.com/bercyinta/status/210961634736599...
12,2026-10-12T12:04:31.000Z,"@polcadaily Hadireeeu, pas bangeet kak ada pro...",https://x.com/anvseongmin/status/2109616201496...
13,2026-10-12T11:06:08.000Z,[Last day]\nVoucher Lazada diskon 15% s/d 1jt\...,https://x.com/AkulahPara/status/21096015053514...
14,2026-10-12T10:35:44.000Z,aduhhh aku udah gatau mau gimana inii,https://x.com/jieabee/status/2109593855800787200
15,2026-10-12T10:33:42.000Z,Ada customer dari kemarin susah dihubungin dan...,https://x.com/jieabee/status/2109593343324008754
16,2026-10-12T09:48:56.000Z,Kayanya nunggu asapnya sampai Jakarta baru deh...,https://x.com/hsf_khn/status/2109582080783024552
17,2026-10-12T09:30:40.000Z,"semua sosmedku aku ""jiea jiea"" in jirr wkwkwkkw",https://x.com/jieabee/status/2109577480478789800

In [51]:

folder_output = Path("/content/output")
folder_output.mkdir(parents=True, exist_ok=True)

file_bersih = folder_output / "dataset_promo_1010_indonesia.csv"
df_id.to_csv(file_bersih, index=False, encoding="utf-8-sig")

print("Dataset tersimpan:", file_bersih)
print("Total baris:", len(df_id))

Dataset tersimpan: /content/output/dataset_promo_1010_indonesia.csv
Total baris: 54

In [52]:

import pandas as pd
from pathlib import Path

file_bersih = Path("/content/output/dataset_promo_1010_indonesia.csv")
df = pd.read_csv(file_bersih)

# Kata kunci untuk pemeriksaan relevansi awal
kata_kunci = [
    "10.10", "10/10", "tanggal kembar",
    "promo", "diskon", "voucher", "gratis ongkir",
    "lazada", "shopee", "tokopedia", "blibli",
    "belanja", "flash sale", "cashback"
]

def cek_relevansi(teks):
    teks = str(teks).lower()
    return any(kata in teks for kata in kata_kunci)

df["indikasi_relevan"] = df["full_text"].apply(cek_relevansi)

print("Total cuitan:", len(df))
print("Terindikasi relevan:", int(df["indikasi_relevan"].sum()))
print("Perlu diperiksa manual:", int((~df["indikasi_relevan"]).sum()))

# Tampilkan seluruh cuitan agar bisa diperiksa
display(df[["created_at", "full_text", "indikasi_relevan"]])

Total cuitan: 54
Terindikasi relevan: 32
Perlu diperiksa manual: 22

,created_at,full_text,indikasi_relevan
0,2026-10-12T16:18:00.000Z,Sewaktu2 suka ada promo 10.10 diskon tagihan l...,True
1,2026-10-12T14:41:51.000Z,"@nnawinss Yukk kak, by req &lt;3 promo 10.10 d...",True
2,2026-10-12T12:59:33.000Z,hari terakhir jajan layout promo 10.10 ‼️ lesg...,True
3,2026-10-12T12:40:52.000Z,"@bercyinta Chibi dibawah kak, promo 10.10",True
4,2026-10-12T12:27:06.000Z,Plis beli disni akuh huhuhhhu,False
5,2026-10-12T12:21:51.000Z,Lama lama ku pake sendiri ni disney duhh,False
6,2026-10-12T12:20:56.000Z,haloo adakah yang mau disney aku jual rugi kar...,False
7,2026-10-12T12:20:50.000Z,@capybavra GEMESSSS WARNANYA MASUP GTUU,False
8,2026-10-12T12:05:06.000Z,Masih adakah layout req promo 10.10? Mau jajan...,True
9,2026-10-12T12:04:31.000Z,"@polcadaily Hadireeeu, pas bangeet kak ada pro...",True
10,2026-10-12T11:06:08.000Z,[Last day]\nVoucher Lazada diskon 15% s/d 1jt\...,True
11,2026-10-12T10:35:44.000Z,aduhhh aku udah gatau mau gimana inii,False
12,2026-10-12T10:33:42.000Z,Ada customer dari kemarin susah dihubungin dan...,False
13,2026-10-12T09:48:56.000Z,Kayanya nunggu asapnya sampai Jakarta baru deh...,True
14,2026-10-12T09:30:40.000Z,"semua sosmedku aku ""jiea jiea"" in jirr wkwkwkkw",False
15,2026-10-12T09:21:14.000Z,LAST DAYYYY. ‼️\nsiapa yg mau jajan layout pro...,True
16,2026-10-12T08:59:21.000Z,100 ml di aku bisa buat 6-8 bulan karena 1 pum...,True
17,2026-10-12T08:52:51.000Z,"@canzdIe @jokitugasnic know your customer, bia...",False
18,2026-10-12T08:47:56.000Z,"ternyata pas dipake malah keliatan clean, eleg...",True
19,2026-10-12T08:37:45.000Z,@shakiraaiy2610 inimah yang rude sellernyaaa,False
20,2026-10-12T08:21:10.000Z,https://t.co/MSZzSnarR5\n\nCo online poprs nya...,True
21,2026-10-12T08:10:20.000Z,@univershan Cwa kak,False
22,2026-10-12T08:10:00.000Z,📌Nambang koin Lazada\n\nTambahan potongan harg...,True
23,2026-10-12T08:06:51.000Z,cwa kakkk\n@moshijoki,False
24,2026-10-12T08:03:57.000Z,males banget nulisss pliss joki tulis yang ku ...,False
25,2026-10-12T08:03:32.000Z,@lov3wh1sper 1 halaman folio berapa kak? bisa ...,False
26,2026-10-12T08:02:41.000Z,@moshijoki @ciyuzzziy berapa kak per halaman? ...,False
27,2026-10-12T08:01:52.000Z,@somzecookie scan aja hasilnya,False
28,2026-10-12T08:01:41.000Z,@somzecookie bisa dl mepet ga kak? Terakhir di...,False
29,2026-10-12T07:56:22.000Z,@mingih kok lu manja gini si &lt;/333 ????? ma...,True
30,2026-10-12T07:02:21.000Z,@yuppipluppy @jokitugasnic ouhh gituu baru tau...,False
31,2026-10-12T06:36:24.000Z,"Hari terakhir. Promo 10.10, saatnya berlanggan...",True
32,2026-10-12T06:30:00.000Z,"Hari terakhir. Promo 10.10, saatnya berlanggan...",True
33,2026-10-12T05:49:59.000Z,@manajemenbobrok heeh padahal kamari promo 10.10,True
34,2026-10-12T04:34:48.000Z,@kaihkamal @hueningkayih Rame banget sampai sa...,True
35,2026-10-12T03:14:10.000Z,"Yukkk jajang layout chibi dibawah, avail for w...",True
36,2026-10-12T03:00:05.000Z,gas ambil promo 10.10\n\nrekomendasi: Live Cla...,True
37,2026-10-12T03:00:01.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,True
38,2026-10-12T02:58:59.000Z,gas ambil promo 10.10\n\nrekomendasi: Live Cla...,True
39,2026-10-12T02:50:30.000Z,"Traveloka gelar Promo 10.10, tawarkan diskon t...",True
40,2026-10-12T02:00:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,True
41,2026-10-12T01:44:38.000Z,"akun ba buat yapping"" gitu boleh kan ya? apa k...",False
42,2026-10-12T01:43:14.000Z,close aja deh ngantuk mau bobo lagiiii,False
43,2026-10-12T01:25:56.000Z,@jokitugasnic siapa tau masih sehat walafiat b...,False
44,2026-10-12T01:25:08.000Z,"@owpages aku dapet harga dari own ku kak, dan ...",False
45,2026-10-12T01:20:54.000Z,@owpages okeey aku perbaikiii,False
46,2026-10-12T01:01:31.000Z,hari terakhir promo 10.10\n\nrekomendasi: Live...,True
47,2026-10-12T01:00:43.000Z,hari terakhir promo 10.10\n\nrekomendasi: Live...,True
48,2026-10-12T00:59:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,True
49,2026-10-11T23:59:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,True
50,2026-10-11T22:58:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,True
51,2026-10-11T21:58:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,True
52,2026-10-11T20:58:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,True
53,2026-10-11T19:57:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,True

In [53]:

import pandas as pd
from pathlib import Path

folder = Path("/content/output")
file_asal = folder / "dataset_promo_1010_indonesia.csv"

df = pd.read_csv(file_asal)
df["full_text"] = df["full_text"].fillna("").astype(str)
teks = df["full_text"].str.lower()

# Indikasi hubungan langsung dengan promo tanggal kembar
pola_1010 = r"10[./ -]?10|tanggal kembar|10 oktober"
pola_promo = r"promo|diskon|voucher|gratis ongkir|cashback|flash sale|belanja|lazada|shopee|tokopedia|traveloka|pahamify"

mask = teks.str.contains(pola_1010, regex=True) & teks.str.contains(pola_promo, regex=True)
df_relevan = df[mask].copy()

jumlah_sebelum = len(df_relevan)

# Hapus duplikat berdasarkan ID, kemudian teks
if "id_str" in df_relevan.columns:
    df_relevan = df_relevan.drop_duplicates(subset=["id_str"])

df_relevan = df_relevan.drop_duplicates(subset=["full_text"])

file_final = folder / "dataset_promo_1010_relevan.csv"
df_relevan.to_csv(file_final, index=False, encoding="utf-8-sig")

print("Data awal:", len(df))
print("Terpilih sebelum hapus duplikat:", jumlah_sebelum)
print("Data relevan unik:", len(df_relevan))
print("Lokasi file:", file_final)

display(df_relevan[["created_at", "full_text"]])

Data awal: 54
Terpilih sebelum hapus duplikat: 32
Data relevan unik: 32
Lokasi file: /content/output/dataset_promo_1010_relevan.csv

,created_at,full_text
0,2026-10-12T16:18:00.000Z,Sewaktu2 suka ada promo 10.10 diskon tagihan l...
1,2026-10-12T14:41:51.000Z,"@nnawinss Yukk kak, by req &lt;3 promo 10.10 d..."
2,2026-10-12T12:59:33.000Z,hari terakhir jajan layout promo 10.10 ‼️ lesg...
3,2026-10-12T12:40:52.000Z,"@bercyinta Chibi dibawah kak, promo 10.10"
8,2026-10-12T12:05:06.000Z,Masih adakah layout req promo 10.10? Mau jajan...
9,2026-10-12T12:04:31.000Z,"@polcadaily Hadireeeu, pas bangeet kak ada pro..."
10,2026-10-12T11:06:08.000Z,[Last day]\nVoucher Lazada diskon 15% s/d 1jt\...
13,2026-10-12T09:48:56.000Z,Kayanya nunggu asapnya sampai Jakarta baru deh...
15,2026-10-12T09:21:14.000Z,LAST DAYYYY. ‼️\nsiapa yg mau jajan layout pro...
16,2026-10-12T08:59:21.000Z,100 ml di aku bisa buat 6-8 bulan karena 1 pum...
18,2026-10-12T08:47:56.000Z,"ternyata pas dipake malah keliatan clean, eleg..."
20,2026-10-12T08:21:10.000Z,https://t.co/MSZzSnarR5\n\nCo online poprs nya...
22,2026-10-12T08:10:00.000Z,📌Nambang koin Lazada\n\nTambahan potongan harg...
29,2026-10-12T07:56:22.000Z,@mingih kok lu manja gini si &lt;/333 ????? ma...
31,2026-10-12T06:36:24.000Z,"Hari terakhir. Promo 10.10, saatnya berlanggan..."
32,2026-10-12T06:30:00.000Z,"Hari terakhir. Promo 10.10, saatnya berlanggan..."
33,2026-10-12T05:49:59.000Z,@manajemenbobrok heeh padahal kamari promo 10.10
34,2026-10-12T04:34:48.000Z,@kaihkamal @hueningkayih Rame banget sampai sa...
35,2026-10-12T03:14:10.000Z,"Yukkk jajang layout chibi dibawah, avail for w..."
36,2026-10-12T03:00:05.000Z,gas ambil promo 10.10\n\nrekomendasi: Live Cla...
37,2026-10-12T03:00:01.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...
38,2026-10-12T02:58:59.000Z,gas ambil promo 10.10\n\nrekomendasi: Live Cla...
39,2026-10-12T02:50:30.000Z,"Traveloka gelar Promo 10.10, tawarkan diskon t..."
40,2026-10-12T02:00:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...
46,2026-10-12T01:01:31.000Z,hari terakhir promo 10.10\n\nrekomendasi: Live...
47,2026-10-12T01:00:43.000Z,hari terakhir promo 10.10\n\nrekomendasi: Live...
48,2026-10-12T00:59:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...
49,2026-10-11T23:59:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...
50,2026-10-11T22:58:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...
51,2026-10-11T21:58:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...
52,2026-10-11T20:58:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...
53,2026-10-11T19:57:00.000Z,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...

In [54]:

import pandas as pd
from pathlib import Path

file_asal = Path("/content/output/dataset_promo_1010_relevan.csv")
df = pd.read_csv(file_asal)

# Kolom untuk pemeriksaan manual
df["jenis_cuitan"] = ""
df["sentimen"] = ""
df["alasan_label"] = ""

# Beri ID agar mudah dibahas dan diperiksa
df.insert(0, "nomor_data", range(1, len(df) + 1))

file_label = Path("/content/output/dataset_promo_1010_pelabelan.csv")
df.to_csv(file_label, index=False, encoding="utf-8-sig")

print("Jumlah data:", len(df))
print("File pelabelan:", file_label)

display(df[["nomor_data", "full_text", "jenis_cuitan", "sentimen"]])

Jumlah data: 32
File pelabelan: /content/output/dataset_promo_1010_pelabelan.csv

,nomor_data,full_text,jenis_cuitan,sentimen
0,1,Sewaktu2 suka ada promo 10.10 diskon tagihan l...,,
1,2,"@nnawinss Yukk kak, by req &lt;3 promo 10.10 d...",,
2,3,hari terakhir jajan layout promo 10.10 ‼️ lesg...,,
3,4,"@bercyinta Chibi dibawah kak, promo 10.10",,
4,5,Masih adakah layout req promo 10.10? Mau jajan...,,
5,6,"@polcadaily Hadireeeu, pas bangeet kak ada pro...",,
6,7,[Last day]\nVoucher Lazada diskon 15% s/d 1jt\...,,
7,8,Kayanya nunggu asapnya sampai Jakarta baru deh...,,
8,9,LAST DAYYYY. ‼️\nsiapa yg mau jajan layout pro...,,
9,10,100 ml di aku bisa buat 6-8 bulan karena 1 pum...,,
10,11,"ternyata pas dipake malah keliatan clean, eleg...",,
11,12,https://t.co/MSZzSnarR5\n\nCo online poprs nya...,,
12,13,📌Nambang koin Lazada\n\nTambahan potongan harg...,,
13,14,@mingih kok lu manja gini si &lt;/333 ????? ma...,,
14,15,"Hari terakhir. Promo 10.10, saatnya berlanggan...",,
15,16,"Hari terakhir. Promo 10.10, saatnya berlanggan...",,
16,17,@manajemenbobrok heeh padahal kamari promo 10.10,,
17,18,@kaihkamal @hueningkayih Rame banget sampai sa...,,
18,19,"Yukkk jajang layout chibi dibawah, avail for w...",,
19,20,gas ambil promo 10.10\n\nrekomendasi: Live Cla...,,
20,21,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,,
21,22,gas ambil promo 10.10\n\nrekomendasi: Live Cla...,,
22,23,"Traveloka gelar Promo 10.10, tawarkan diskon t...",,
23,24,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,,
24,25,hari terakhir promo 10.10\n\nrekomendasi: Live...,,
25,26,hari terakhir promo 10.10\n\nrekomendasi: Live...,,
26,27,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,,
27,28,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,,
28,29,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,,
29,30,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,,
30,31,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,,
31,32,Kode Diskon Promo Pahamify 09 - 11 Oktober 202...,,

In [56]:
# Tampilkan 5 cuitan pertama secara lengkap
for _, baris in df.head(5).iterrows():
    print(f"\nNomor: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 50)

Nomor: 1
Sewaktu2 suka ada promo 10.10 diskon tagihan listrik &amp; pulsa qris serba seribu di apk ShopeePay. Buat yg baru install, yuk pakai kode referal biar dpt free saldo Rp 5000

Caranya:
1. Gunakan kode referral ShopeePay SNVQTRYVM saat regis
2. Lengkapi data/upgrade ke ShopeePay Plus https://t.co/1bKgPHWNBn
--------------------------------------------------

Nomor: 2
@nnawinss Yukk kak, by req &lt;3 promo 10.10 diskon 10% nih
--------------------------------------------------

Nomor: 3
hari terakhir jajan layout promo 10.10 ‼️ lesgoooo. #bealanja
--------------------------------------------------

Nomor: 4
@bercyinta Chibi dibawah kak, promo 10.10
--------------------------------------------------

Nomor: 5
Masih adakah layout req promo 10.10? Mau jajan req mari #zonauang
--------------------------------------------------

In [57]:

# Isi label untuk 5 cuitan pertama
label_awal = {
    1: ("Promosi", "Netral"),
    2: ("Promosi", "Netral"),
    3: ("Lainnya", "Tidak cukup konteks"),
    4: ("Lainnya", "Tidak cukup konteks"),
    5: ("Lainnya", "Tidak cukup konteks")
}

for nomor, (jenis, sentimen) in label_awal.items():
    df.loc[df["nomor_data"] == nomor, "jenis_cuitan"] = jenis
    df.loc[df["nomor_data"] == nomor, "sentimen"] = sentimen

# Simpan perubahan
df.to_csv(
    "/content/output/dataset_promo_1010_pelabelan.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Label nomor 1–5 berhasil disimpan!")
display(df[["nomor_data", "jenis_cuitan", "sentimen"]].head(5))

Label nomor 1–5 berhasil disimpan!

/tmp/ipykernel_5483/2521754605.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Promosi' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df["nomor_data"] == nomor, "jenis_cuitan"] = jenis
/tmp/ipykernel_5483/2521754605.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Netral' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df["nomor_data"] == nomor, "sentimen"] = sentimen

   nomor_data jenis_cuitan             sentimen
0           1      Promosi               Netral
1           2      Promosi               Netral
2           3      Lainnya  Tidak cukup konteks
3           4      Lainnya  Tidak cukup konteks
4           5      Lainnya  Tidak cukup konteks

In [58]:

for _, baris in df[df["nomor_data"].between(6, 10)].iterrows():
    print(f"\nNomor: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 50)

Nomor: 6
@polcadaily Hadireeeu, pas bangeet kak ada promo 10.10 juga :3 intip dibawah yuk
--------------------------------------------------

Nomor: 7
[Last day]
Voucher Lazada diskon 15% s/d 1jt
🗓 12 Okt

Klaim semua vouchernya di sini
https://t.co/vtSBIP7Ajm
DAN di sini
https://t.co/4NH9VKnlSW

Promo 10.10
https://t.co/tjTn7lF7r9 https://t.co/f24H7cck7w
--------------------------------------------------

Nomor: 8
Kayanya nunggu asapnya sampai Jakarta baru deh jadi Bencana Nasional, mau? Mumpung masih ada promo 10.10
--------------------------------------------------

Nomor: 9
LAST DAYYYY. ‼️
siapa yg mau jajan layout promo 10.10 masih bisa yaaa! #bealanja
--------------------------------------------------

Nomor: 10
100 ml di aku bisa buat 6-8 bulan karena 1 pump cukup buat semuka. 100k dapet 3 item🤤 ini kemarin promo 10.10 (plis cosrx endorse ak) https://t.co/UIVslPWdBQ
--------------------------------------------------

In [59]:

label_6_10 = {
    6: ("Promosi", "Netral"),
    7: ("Promosi", "Netral"),
    8: ("Lainnya", "Tidak cukup konteks"),
    9: ("Lainnya", "Tidak cukup konteks"),
    10: ("Konsumen", "Positif")
}

for nomor, (jenis, sentimen) in label_6_10.items():
    df.loc[df["nomor_data"] == nomor, "jenis_cuitan"] = jenis
    df.loc[df["nomor_data"] == nomor, "sentimen"] = sentimen

df.to_csv(
    "/content/output/dataset_promo_1010_pelabelan.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Label nomor 6–10 berhasil disimpan!")
display(df[df["nomor_data"].between(6, 10)][
    ["nomor_data", "jenis_cuitan", "sentimen"]
])

Label nomor 6–10 berhasil disimpan!

   nomor_data jenis_cuitan             sentimen
5           6      Promosi               Netral
6           7      Promosi               Netral
7           8      Lainnya  Tidak cukup konteks
8           9      Lainnya  Tidak cukup konteks
9          10     Konsumen              Positif

In [60]:
for _, baris in df[df["nomor_data"].between(11, 20)].iterrows():
    print(f"\nNomor: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 60)

Nomor: 11
ternyata pas dipake malah keliatan clean, elegan, dan adem banget. Bener-bener susah buat nggak jatuh hati🥹

Cek disini lagi promo 10.10⤵️
🔗 https://t.co/LeddHVEfEO
🔗 https://t.co/LeddHVEfEO
------------------------------------------------------------

Nomor: 12
https://t.co/MSZzSnarR5

Co online poprs nya silah kan
Lg promo 10.10

#gay #gayjatim #gaymakassar
------------------------------------------------------------

Nomor: 13
📌Nambang koin Lazada

Tambahan potongan harga
https://t.co/ch4ncAmAaf
(buku, Skincare, produk lain juga banyak)

✅Mumpung masih promo 10.10 https://t.co/30MMPu3tgE
------------------------------------------------------------

Nomor: 14
@mingih kok lu manja gini si &lt;/333 ????? masa gw hrus beli kalender 2027 skrang juga? promo 10.10 udah lewat ,,
------------------------------------------------------------

Nomor: 15
Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu. https://t.co/gLL6w3LwJ9
------------------------------------------------------------

Nomor: 16
Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu.

Khusus pelanggan baru, promo ini berlaku 10–12 Oktober 2026. https://t.co/R7awStkC7f
------------------------------------------------------------

Nomor: 17
@manajemenbobrok heeh padahal kamari promo 10.10
------------------------------------------------------------

Nomor: 18
@kaihkamal @hueningkayih Rame banget sampai saya bingung cara scroll mentab 😥😥. Mau bantu saya? Saya ada promo 10.10 kemarin, tapi kayaknya kamu kehabisan soalnya udah ganti tanggal. Minat promo apa lagi?
------------------------------------------------------------

Nomor: 19
Yukkk jajang layout chibi dibawah, avail for wabis dan wpp. By req yaaa, ada promo 10.10 disc 10%

#zonauang
------------------------------------------------------------

Nomor: 20
gas ambil promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/JlRtW95rjx
------------------------------------------------------------

In [62]:

label_11_20 = {
    11: ("Konsumen", "Positif"),
    12: ("Lainnya", "Tidak cukup konteks"),
    13: ("Promosi", "Netral"),
    14: ("Percakapan", "Negatif"),
    15: ("Promosi", "Netral"),
    16: ("Promosi", "Netral"),
    17: ("Percakapan", "Tidak cukup konteks"),
    18: ("Percakapan", "Tidak cukup konteks"),
    19: ("Lainnya", "Tidak cukup konteks"),
    20: ("Promosi", "Netral")
}

for nomor, (jenis, sentimen) in label_11_20.items():
    df.loc[df["nomor_data"] == nomor, "jenis_cuitan"] = jenis
    df.loc[df["nomor_data"] == nomor, "sentimen"] = sentimen

df.to_csv(
    "/content/output/dataset_promo_1010_pelabelan.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Label nomor 11–20 berhasil disimpan!")
display(df[df["nomor_data"].between(11, 20)][
    ["nomor_data", "jenis_cuitan", "sentimen"]
])

Label nomor 11–20 berhasil disimpan!

    nomor_data jenis_cuitan             sentimen
10          11     Konsumen              Positif
11          12      Lainnya  Tidak cukup konteks
12          13      Promosi               Netral
13          14   Percakapan              Negatif
14          15      Promosi               Netral
15          16      Promosi               Netral
16          17   Percakapan  Tidak cukup konteks
17          18   Percakapan  Tidak cukup konteks
18          19      Lainnya  Tidak cukup konteks
19          20      Promosi               Netral

In [63]:
for _, baris in df[df["nomor_data"].between(21, 30)].iterrows():
    print(f"\nNomor: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 60)

Nomor: 21
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/kQcIA5ukCm
------------------------------------------------------------

Nomor: 22
gas ambil promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/aCAbVLKXw9
------------------------------------------------------------

Nomor: 23
Traveloka gelar Promo 10.10, tawarkan diskon tiket di 8 negara  https://t.co/066SxwTmDa
------------------------------------------------------------

Nomor: 24
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/8dnh7zyp3n
------------------------------------------------------------

Nomor: 25
hari terakhir promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/9ALgNZVL0U
------------------------------------------------------------

Nomor: 26
hari terakhir promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/DHgBaFW8op
------------------------------------------------------------

Nomor: 27
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/eZXFHnPrCi
------------------------------------------------------------

Nomor: 28
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/ukc47FF4KQ
------------------------------------------------------------

Nomor: 29
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/l0ZY41esku
------------------------------------------------------------

Nomor: 30
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqj5HA
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/ZeAGtblrh4
------------------------------------------------------------

In [64]:

label_21_30 = {
    nomor: ("Promosi", "Netral")
    for nomor in range(21, 31)
}

for nomor, (jenis, sentimen) in label_21_30.items():
    df.loc[df["nomor_data"] == nomor, "jenis_cuitan"] = jenis
    df.loc[df["nomor_data"] == nomor, "sentimen"] = sentimen

df.to_csv(
    "/content/output/dataset_promo_1010_pelabelan.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Label nomor 21–30 berhasil disimpan!")
display(df[df["nomor_data"].between(21, 30)][
    ["nomor_data", "jenis_cuitan", "sentimen"]
])

Label nomor 21–30 berhasil disimpan!

    nomor_data jenis_cuitan sentimen
20          21      Promosi   Netral
21          22      Promosi   Netral
22          23      Promosi   Netral
23          24      Promosi   Netral
24          25      Promosi   Netral
25          26      Promosi   Netral
26          27      Promosi   Netral
27          28      Promosi   Netral
28          29      Promosi   Netral
29          30      Promosi   Netral

In [65]:

for _, baris in df[df["nomor_data"].between(31, 32)].iterrows():
    print(f"\nNomor: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 60)

Nomor: 31
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqj5HA
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/oSeY97lUfi
------------------------------------------------------------

Nomor: 32
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/7WJKHCviMW
------------------------------------------------------------

In [66]:

print("Jumlah seluruh data:", len(df))
print("\nJumlah berdasarkan jenis cuitan:")
print(df["jenis_cuitan"].value_counts(dropna=False))

print("\nJumlah berdasarkan sentimen:")
print(df["sentimen"].value_counts(dropna=False))

Jumlah seluruh data: 32

Jumlah berdasarkan jenis cuitan:
jenis_cuitan
Promosi       18
Lainnya        7
Percakapan     3
Konsumen       2
NaN            2
Name: count, dtype: int64

Jumlah berdasarkan sentimen:
sentimen
Netral                 18
Tidak cukup konteks     9
Positif                 2
NaN                     2
Negatif                 1
Name: count, dtype: int64

In [68]:

# Tampilkan data yang labelnya masih kosong
display(
    df[df["jenis_cuitan"].isna() | df["sentimen"].isna()][
        ["nomor_data", "full_text", "jenis_cuitan", "sentimen"]
    ]
)

,nomor_data,full_text,jenis_cuitan,sentimen
30,31,Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\n\n❓Tutorial dapetin promo:\n1️⃣ Buka website https://t.co/y4qQvqj5HA\n2️⃣ Pilih paket belajar yang kamu inginkan\n3️⃣ Apply kode promo 10.10\n4️⃣ Masukan kode promo PFMMERI\n\n#pahamify #utbk #tka #bimbelonline #agit https://t....,NaN,NaN
31,32,Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\n\n❓Tutorial dapetin promo:\n1️⃣ Buka website https://t.co/y4qQvqjDx8\n2️⃣ Pilih paket belajar yang kamu inginkan\n3️⃣ Apply kode promo 10.10\n4️⃣ Masukan kode promo PFMMERI\n\n#pahamify #utbk #tka #bimbelonline #agit https://t....,NaN,NaN

In [69]:

# Lengkapi label nomor 31 dan 32
df.loc[df["nomor_data"].isin([31, 32]), "jenis_cuitan"] = "Promosi"
df.loc[df["nomor_data"].isin([31, 32]), "sentimen"] = "Netral"

# Simpan kembali file pelabelan
df.to_csv(
    "/content/output/dataset_promo_1010_pelabelan.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Label nomor 31 dan 32 sudah dilengkapi.")

display(df[df["nomor_data"].isin([31, 32])][
    ["nomor_data", "jenis_cuitan", "sentimen"]
])

Label nomor 31 dan 32 sudah dilengkapi.

    nomor_data jenis_cuitan sentimen
30          31      Promosi   Netral
31          32      Promosi   Netral

In [70]:

print("Label jenis cuitan yang kosong:", df["jenis_cuitan"].isna().sum())
print("Label sentimen yang kosong:", df["sentimen"].isna().sum())

Label jenis cuitan yang kosong: 0
Label sentimen yang kosong: 0

In [71]:

# Ringkasan jenis cuitan dan sentimen
print("RINGKASAN JENIS CUITAN")
display(df["jenis_cuitan"].value_counts().rename_axis("jenis_cuitan").reset_index(name="jumlah"))

print("\nRINGKASAN SENTIMEN")
display(df["sentimen"].value_counts().rename_axis("sentimen").reset_index(name="jumlah"))

print("\nCUITAN YANG DILABELI SEBAGAI KONSUMEN")
display(
    df[df["jenis_cuitan"] == "Konsumen"][
        ["nomor_data", "full_text", "sentimen"]
    ]
)

RINGKASAN JENIS CUITAN

  jenis_cuitan  jumlah
0      Promosi      20
1      Lainnya       7
2   Percakapan       3
3     Konsumen       2

RINGKASAN SENTIMEN

              sentimen  jumlah
0               Netral      20
1  Tidak cukup konteks       9
2              Positif       2
3              Negatif       1

CUITAN YANG DILABELI SEBAGAI KONSUMEN

,nomor_data,full_text,sentimen
9,10,100 ml di aku bisa buat 6-8 bulan karena 1 pump cukup buat semuka. 100k dapet 3 item🤤 ini kemarin promo 10.10 (plis cosrx endorse ak) https://t.co/UIVslPWdBQ,Positif
10,11,"ternyata pas dipake malah keliatan clean, elegan, dan adem banget. Bener-bener susah buat nggak jatuh hati🥹\n\nCek disini lagi promo 10.10⤵️\n🔗 https://t.co/LeddHVEfEO\n🔗 https://t.co/LeddHVEfEO",Positif

In [72]:

# Tampilkan cuitan yang bukan kategori "Lainnya"
# agar kita bisa memeriksa kemungkinan opini konsumen lain
display(
    df[df["jenis_cuitan"] != "Lainnya"][
        ["nomor_data", "jenis_cuitan", "sentimen", "full_text"]
    ].to_string(index=False)
)

' nomor_data jenis_cuitan            sentimen                                                                                                                                                                                                                                                                                                                   full_text\n          1      Promosi              Netral     Sewaktu2 suka ada promo 10.10 diskon tagihan listrik &amp; pulsa qris serba seribu di apk ShopeePay. Buat yg baru install, yuk pakai kode referal biar dpt free saldo Rp 5000\\n\\nCaranya: \\n1. Gunakan kode referral ShopeePay SNVQTRYVM saat regis\\n2. Lengkapi data/upgrade ke ShopeePay Plus https://t.co/1bKgPHWNBn\n          2      Promosi              Netral                                                                                                                                                                                                                                                                 @nnawinss Yukk kak, by req &lt;3 promo 10.10 diskon 10% nih\n          6      Promosi              Netral                                                                                                                                                                                                                                            @polcadaily Hadireeeu, pas bangeet kak ada promo 10.10 juga :3 intip dibawah yuk\n          7      Promosi              Netral                                                                                                    [Last day]\\nVoucher Lazada diskon 15% s/d 1jt\\n🗓 12 Okt\\n\\nKlaim semua vouchernya di sini\\nhttps://t.co/vtSBIP7Ajm\\nDAN di sini\\nhttps://t.co/4NH9VKnlSW\\n\\nPromo 10.10\\nhttps://t.co/tjTn7lF7r9 https://t.co/f24H7cck7w\n         10     Konsumen             Positif                                                                                                                                                               100 ml di aku bisa buat 6-8 bulan karena 1 pump cukup buat semuka. 100k dapet 3 item🤤 ini kemarin promo 10.10 (plis cosrx endorse ak) https://t.co/UIVslPWdBQ\n         11     Konsumen             Positif                                                                                                                          ternyata pas dipake malah keliatan clean, elegan, dan adem banget. Bener-bener susah buat nggak jatuh hati🥹\\n\\nCek disini lagi promo 10.10⤵️\\n🔗 https://t.co/LeddHVEfEO\\n🔗 https://t.co/LeddHVEfEO\n         13      Promosi              Netral                                                                                                                                                   📌Nambang koin Lazada\\n\\nTambahan potongan harga\\nhttps://t.co/ch4ncAmAaf\\n(buku, Skincare, produk lain juga banyak)\\n\\n✅Mumpung masih promo 10.10 https://t.co/30MMPu3tgE\n         14   Percakapan             Negatif                                                                                                                                                                                                          @mingih kok lu manja gini si &lt;/333 ????? masa gw hrus beli kalender 2027 skrang juga? promo 10.10 udah lewat ,,\n         15      Promosi              Netral                                                                                Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu. https://t.co/gLL6w3LwJ9\n         16      Promosi              Netral                Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu.\\n\\nKhusus pelanggan baru, promo ini berlaku 10–12 Oktober 2026. https://t.co/R7awStkC7f\n         17   Percakapan Tidak cukup konteks                                                                                                                                                                                                                                                                            @manajemenbobrok heeh padahal kamari promo 10.10\n         18   Percakapan Tidak cukup konteks                                                                                                                @kaihkamal @hueningkayih Rame banget sampai saya bingung cara scroll mentab 😥😥. Mau bantu saya? Saya ada promo 10.10 kemarin, tapi kayaknya kamu kehabisan soalnya udah ganti tanggal. Minat promo apa lagi?\n         20      Promosi              Netral     gas ambil promo 10.10\\n\\nrekomendasi: Live Class &amp; Prime UTBK\\n\\ncek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo\\n\\nkode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/JlRtW95rjx\n         21      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqjDx8\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/kQcIA5ukCm\n         22      Promosi              Netral     gas ambil promo 10.10\\n\\nrekomendasi: Live Class &amp; Prime UTBK\\n\\ncek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo\\n\\nkode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/aCAbVLKXw9\n         23      Promosi              Netral                                                                                                                                                                                                                                     Traveloka gelar Promo 10.10, tawarkan diskon tiket di 8 negara  https://t.co/066SxwTmDa\n         24      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqjDx8\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/8dnh7zyp3n\n         25      Promosi              Netral hari terakhir promo 10.10\\n\\nrekomendasi: Live Class &amp; Prime UTBK\\n\\ncek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo\\n\\nkode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/9ALgNZVL0U\n         26      Promosi              Netral hari terakhir promo 10.10\\n\\nrekomendasi: Live Class &amp; Prime UTBK\\n\\ncek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo\\n\\nkode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/DHgBaFW8op\n         27      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqjDx8\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/eZXFHnPrCi\n         28      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqjDx8\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/ukc47FF4KQ\n         29      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqjDx8\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/l0ZY41esku\n         30      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqj5HA\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/ZeAGtblrh4\n         31      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqj5HA\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/oSeY97lUfi\n         32      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqjDx8\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/7WJKHCviMW'

In [73]:

for _, baris in df.iterrows():
    print(f"\nNomor: {baris['nomor_data']}")
    print(f"Jenis: {baris['jenis_cuitan']} | Sentimen: {baris['sentimen']}")
    print(f"Cuitan: {baris['full_text']}")
    print("-" * 60)

Nomor: 1
Jenis: Promosi | Sentimen: Netral
Cuitan: Sewaktu2 suka ada promo 10.10 diskon tagihan listrik &amp; pulsa qris serba seribu di apk ShopeePay. Buat yg baru install, yuk pakai kode referal biar dpt free saldo Rp 5000

Caranya:
1. Gunakan kode referral ShopeePay SNVQTRYVM saat regis
2. Lengkapi data/upgrade ke ShopeePay Plus https://t.co/1bKgPHWNBn
------------------------------------------------------------

Nomor: 2
Jenis: Promosi | Sentimen: Netral
Cuitan: @nnawinss Yukk kak, by req &lt;3 promo 10.10 diskon 10% nih
------------------------------------------------------------

Nomor: 3
Jenis: Lainnya | Sentimen: Tidak cukup konteks
Cuitan: hari terakhir jajan layout promo 10.10 ‼️ lesgoooo. #bealanja
------------------------------------------------------------

Nomor: 4
Jenis: Lainnya | Sentimen: Tidak cukup konteks
Cuitan: @bercyinta Chibi dibawah kak, promo 10.10
------------------------------------------------------------

Nomor: 5
Jenis: Lainnya | Sentimen: Tidak cukup konteks
Cuitan: Masih adakah layout req promo 10.10? Mau jajan req mari #zonauang
------------------------------------------------------------

Nomor: 6
Jenis: Promosi | Sentimen: Netral
Cuitan: @polcadaily Hadireeeu, pas bangeet kak ada promo 10.10 juga :3 intip dibawah yuk
------------------------------------------------------------

Nomor: 7
Jenis: Promosi | Sentimen: Netral
Cuitan: [Last day]
Voucher Lazada diskon 15% s/d 1jt
🗓 12 Okt

Klaim semua vouchernya di sini
https://t.co/vtSBIP7Ajm
DAN di sini
https://t.co/4NH9VKnlSW

Promo 10.10
https://t.co/tjTn7lF7r9 https://t.co/f24H7cck7w
------------------------------------------------------------

Nomor: 8
Jenis: Lainnya | Sentimen: Tidak cukup konteks
Cuitan: Kayanya nunggu asapnya sampai Jakarta baru deh jadi Bencana Nasional, mau? Mumpung masih ada promo 10.10
------------------------------------------------------------

Nomor: 9
Jenis: Lainnya | Sentimen: Tidak cukup konteks
Cuitan: LAST DAYYYY. ‼️
siapa yg mau jajan layout promo 10.10 masih bisa yaaa! #bealanja
------------------------------------------------------------

Nomor: 10
Jenis: Konsumen | Sentimen: Positif
Cuitan: 100 ml di aku bisa buat 6-8 bulan karena 1 pump cukup buat semuka. 100k dapet 3 item🤤 ini kemarin promo 10.10 (plis cosrx endorse ak) https://t.co/UIVslPWdBQ
------------------------------------------------------------

Nomor: 11
Jenis: Konsumen | Sentimen: Positif
Cuitan: ternyata pas dipake malah keliatan clean, elegan, dan adem banget. Bener-bener susah buat nggak jatuh hati🥹

Cek disini lagi promo 10.10⤵️
🔗 https://t.co/LeddHVEfEO
🔗 https://t.co/LeddHVEfEO
------------------------------------------------------------

Nomor: 12
Jenis: Lainnya | Sentimen: Tidak cukup konteks
Cuitan: https://t.co/MSZzSnarR5

Co online poprs nya silah kan
Lg promo 10.10

#gay #gayjatim #gaymakassar
------------------------------------------------------------

Nomor: 13
Jenis: Promosi | Sentimen: Netral
Cuitan: 📌Nambang koin Lazada

Tambahan potongan harga
https://t.co/ch4ncAmAaf
(buku, Skincare, produk lain juga banyak)

✅Mumpung masih promo 10.10 https://t.co/30MMPu3tgE
------------------------------------------------------------

Nomor: 14
Jenis: Percakapan | Sentimen: Negatif
Cuitan: @mingih kok lu manja gini si &lt;/333 ????? masa gw hrus beli kalender 2027 skrang juga? promo 10.10 udah lewat ,,
------------------------------------------------------------

Nomor: 15
Jenis: Promosi | Sentimen: Netral
Cuitan: Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu. https://t.co/gLL6w3LwJ9
------------------------------------------------------------

Nomor: 16
Jenis: Promosi | Sentimen: Netral
Cuitan: Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu.

Khusus pelanggan baru, promo ini berlaku 10–12 Oktober 2026. https://t.co/R7awStkC7f
------------------------------------------------------------

Nomor: 17
Jenis: Percakapan | Sentimen: Tidak cukup konteks
Cuitan: @manajemenbobrok heeh padahal kamari promo 10.10
------------------------------------------------------------

Nomor: 18
Jenis: Percakapan | Sentimen: Tidak cukup konteks
Cuitan: @kaihkamal @hueningkayih Rame banget sampai saya bingung cara scroll mentab 😥😥. Mau bantu saya? Saya ada promo 10.10 kemarin, tapi kayaknya kamu kehabisan soalnya udah ganti tanggal. Minat promo apa lagi?
------------------------------------------------------------

Nomor: 19
Jenis: Lainnya | Sentimen: Tidak cukup konteks
Cuitan: Yukkk jajang layout chibi dibawah, avail for wabis dan wpp. By req yaaa, ada promo 10.10 disc 10%

#zonauang
------------------------------------------------------------

Nomor: 20
Jenis: Promosi | Sentimen: Netral
Cuitan: gas ambil promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/JlRtW95rjx
------------------------------------------------------------

Nomor: 21
Jenis: Promosi | Sentimen: Netral
Cuitan: Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/kQcIA5ukCm
------------------------------------------------------------

Nomor: 22
Jenis: Promosi | Sentimen: Netral
Cuitan: gas ambil promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/aCAbVLKXw9
------------------------------------------------------------

Nomor: 23
Jenis: Promosi | Sentimen: Netral
Cuitan: Traveloka gelar Promo 10.10, tawarkan diskon tiket di 8 negara  https://t.co/066SxwTmDa
------------------------------------------------------------

Nomor: 24
Jenis: Promosi | Sentimen: Netral
Cuitan: Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/8dnh7zyp3n
------------------------------------------------------------

Nomor: 25
Jenis: Promosi | Sentimen: Netral
Cuitan: hari terakhir promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/9ALgNZVL0U
------------------------------------------------------------

Nomor: 26
Jenis: Promosi | Sentimen: Netral
Cuitan: hari terakhir promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/DHgBaFW8op
------------------------------------------------------------

Nomor: 27
Jenis: Promosi | Sentimen: Netral
Cuitan: Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/eZXFHnPrCi
------------------------------------------------------------

Nomor: 28
Jenis: Promosi | Sentimen: Netral
Cuitan: Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/ukc47FF4KQ
------------------------------------------------------------

Nomor: 29
Jenis: Promosi | Sentimen: Netral
Cuitan: Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/l0ZY41esku
------------------------------------------------------------

Nomor: 30
Jenis: Promosi | Sentimen: Netral
Cuitan: Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqj5HA
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/ZeAGtblrh4
------------------------------------------------------------

Nomor: 31
Jenis: Promosi | Sentimen: Netral
Cuitan: Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqj5HA
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/oSeY97lUfi
------------------------------------------------------------

Nomor: 32
Jenis: Promosi | Sentimen: Netral
Cuitan: Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/7WJKHCviMW
------------------------------------------------------------

In [74]:

import re
import pandas as pd

def bersihkan_teks(teks):
    teks = str(teks).lower()
    teks = re.sub(r'https?://\S+|www\.\S+', ' ', teks)
    teks = re.sub(r'@\w+', ' ', teks)
    teks = re.sub(r'&amp;', 'dan', teks)
    teks = re.sub(r'[^a-z0-9\s]', ' ', teks)
    teks = re.sub(r'\s+', ' ', teks).strip()
    return teks

df["teks_normalisasi"] = df["full_text"].apply(bersihkan_teks)

print("Jumlah data awal:", len(df))
print("Jumlah teks unik:", df["teks_normalisasi"].nunique())
print("Jumlah teks berulang:",
      len(df) - df["teks_normalisasi"].nunique())

print("\nContoh teks yang berulang:")
frekuensi = df["teks_normalisasi"].value_counts()
display(frekuensi[frekuensi > 1].reset_index().rename(
    columns={
        "index": "teks_normalisasi",
        "teks_normalisasi": "jumlah"
    }
))

Jumlah data awal: 32
Jumlah teks unik: 23
Jumlah teks berulang: 9

Contoh teks yang berulang:

,jumlah,count
0,kode diskon promo pahamify 09 11 oktober 2026 pfmmeri dan 10 10 tutorial dapetin promo 1 buka website 2 pilih paket belajar yang kamu inginkan 3 apply kode promo 10 10 4 masukan kode promo pfmmeri pahamify utbk tka bimbelonline agit,8
1,gas ambil promo 10 10 rekomendasi live class dan prime utbk cek dan beli di web yang ada di poster masukan kode pfmsiaptoptn buat klaim promo kode diskon pahamify mipy bimbel online utbk snbt tka simak ui ujian mandiri ugm itb unpad its ipb um undip belajar online tryout,2
2,hari terakhir promo 10 10 rekomendasi live class dan prime utbk cek dan beli di web yang ada di poster masukan kode pfmsiaptoptn buat klaim promo kode diskon pahamify mipy bimbel online utbk snbt tka simak ui ujian mandiri ugm itb unpad its ipb um undip belajar online tryout,2

In [75]:

from pathlib import Path

# Buat salinan dataset untuk dibersihkan
df_bersih = df.drop_duplicates(
    subset=["teks_normalisasi"],
    keep="first"
).copy()

# Simpan dataset hasil deduplikasi
file_bersih = Path("/content/output/dataset_promo_1010_tanpa_duplikat.csv")
df_bersih.to_csv(file_bersih, index=False, encoding="utf-8-sig")

print("Jumlah data awal:", len(df))
print("Jumlah data setelah deduplikasi:", len(df_bersih))
print("Data yang dihapus karena teks duplikat:", len(df) - len(df_bersih))
print("File tersimpan di:", file_bersih)

Jumlah data awal: 32
Jumlah data setelah deduplikasi: 23
Data yang dihapus karena teks duplikat: 9
File tersimpan di: /content/output/dataset_promo_1010_tanpa_duplikat.csv

In [76]:
display(
    df_bersih[
        ["nomor_data", "jenis_cuitan", "sentimen", "full_text"]
    ].to_string(index=False)
)

' nomor_data jenis_cuitan            sentimen                                                                                                                                                                                                                                                                                                                   full_text\n          1      Promosi              Netral     Sewaktu2 suka ada promo 10.10 diskon tagihan listrik &amp; pulsa qris serba seribu di apk ShopeePay. Buat yg baru install, yuk pakai kode referal biar dpt free saldo Rp 5000\\n\\nCaranya: \\n1. Gunakan kode referral ShopeePay SNVQTRYVM saat regis\\n2. Lengkapi data/upgrade ke ShopeePay Plus https://t.co/1bKgPHWNBn\n          2      Promosi              Netral                                                                                                                                                                                                                                                                 @nnawinss Yukk kak, by req &lt;3 promo 10.10 diskon 10% nih\n          3      Lainnya Tidak cukup konteks                                                                                                                                                                                                                                                               hari terakhir jajan layout promo 10.10 ‼️ lesgoooo. #bealanja\n          4      Lainnya Tidak cukup konteks                                                                                                                                                                                                                                                                                   @bercyinta Chibi dibawah kak, promo 10.10\n          5      Lainnya Tidak cukup konteks                                                                                                                                                                                                                                                           Masih adakah layout req promo 10.10? Mau jajan req mari #zonauang\n          6      Promosi              Netral                                                                                                                                                                                                                                            @polcadaily Hadireeeu, pas bangeet kak ada promo 10.10 juga :3 intip dibawah yuk\n          7      Promosi              Netral                                                                                                    [Last day]\\nVoucher Lazada diskon 15% s/d 1jt\\n🗓 12 Okt\\n\\nKlaim semua vouchernya di sini\\nhttps://t.co/vtSBIP7Ajm\\nDAN di sini\\nhttps://t.co/4NH9VKnlSW\\n\\nPromo 10.10\\nhttps://t.co/tjTn7lF7r9 https://t.co/f24H7cck7w\n          8      Lainnya Tidak cukup konteks                                                                                                                                                                                                                    Kayanya nunggu asapnya sampai Jakarta baru deh jadi Bencana Nasional, mau? Mumpung masih ada promo 10.10\n          9      Lainnya Tidak cukup konteks                                                                                                                                                                                                                                           LAST DAYYYY. ‼️\\nsiapa yg mau jajan layout promo 10.10 masih bisa yaaa! #bealanja\n         10     Konsumen             Positif                                                                                                                                                               100 ml di aku bisa buat 6-8 bulan karena 1 pump cukup buat semuka. 100k dapet 3 item🤤 ini kemarin promo 10.10 (plis cosrx endorse ak) https://t.co/UIVslPWdBQ\n         11     Konsumen             Positif                                                                                                                          ternyata pas dipake malah keliatan clean, elegan, dan adem banget. Bener-bener susah buat nggak jatuh hati🥹\\n\\nCek disini lagi promo 10.10⤵️\\n🔗 https://t.co/LeddHVEfEO\\n🔗 https://t.co/LeddHVEfEO\n         12      Lainnya Tidak cukup konteks                                                                                                                                                                                                                    https://t.co/MSZzSnarR5\\n\\nCo online poprs nya silah kan \\nLg promo 10.10\\n\\n#gay #gayjatim #gaymakassar\n         13      Promosi              Netral                                                                                                                                                   📌Nambang koin Lazada\\n\\nTambahan potongan harga\\nhttps://t.co/ch4ncAmAaf\\n(buku, Skincare, produk lain juga banyak)\\n\\n✅Mumpung masih promo 10.10 https://t.co/30MMPu3tgE\n         14   Percakapan             Negatif                                                                                                                                                                                                          @mingih kok lu manja gini si &lt;/333 ????? masa gw hrus beli kalender 2027 skrang juga? promo 10.10 udah lewat ,,\n         15      Promosi              Netral                                                                                Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu. https://t.co/gLL6w3LwJ9\n         16      Promosi              Netral                Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu.\\n\\nKhusus pelanggan baru, promo ini berlaku 10–12 Oktober 2026. https://t.co/R7awStkC7f\n         17   Percakapan Tidak cukup konteks                                                                                                                                                                                                                                                                            @manajemenbobrok heeh padahal kamari promo 10.10\n         18   Percakapan Tidak cukup konteks                                                                                                                @kaihkamal @hueningkayih Rame banget sampai saya bingung cara scroll mentab 😥😥. Mau bantu saya? Saya ada promo 10.10 kemarin, tapi kayaknya kamu kehabisan soalnya udah ganti tanggal. Minat promo apa lagi?\n         19      Lainnya Tidak cukup konteks                                                                                                                                                                                                              Yukkk jajang layout chibi dibawah, avail for wabis dan wpp. By req yaaa, ada promo 10.10 disc 10%\\n\\n#zonauang\n         20      Promosi              Netral     gas ambil promo 10.10\\n\\nrekomendasi: Live Class &amp; Prime UTBK\\n\\ncek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo\\n\\nkode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/JlRtW95rjx\n         21      Promosi              Netral       Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\\n\\n❓Tutorial dapetin promo:\\n1️⃣ Buka website https://t.co/y4qQvqjDx8\\n2️⃣ Pilih paket belajar yang kamu inginkan\\n3️⃣ Apply kode promo 10.10\\n4️⃣ Masukan kode promo PFMMERI\\n\\n#pahamify #utbk #tka #bimbelonline #agit https://t.co/kQcIA5ukCm\n         23      Promosi              Netral                                                                                                                                                                                                                                     Traveloka gelar Promo 10.10, tawarkan diskon tiket di 8 negara  https://t.co/066SxwTmDa\n         25      Promosi              Netral hari terakhir promo 10.10\\n\\nrekomendasi: Live Class &amp; Prime UTBK\\n\\ncek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo\\n\\nkode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/9ALgNZVL0U'

In [77]:

for _, baris in df_bersih.head(5).iterrows():
    print(f"\nNomor data: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 40)

Nomor data: 1
Sewaktu2 suka ada promo 10.10 diskon tagihan listrik &amp; pulsa qris serba seribu di apk ShopeePay. Buat yg baru install, yuk pakai kode referal biar dpt free saldo Rp 5000

Caranya:
1. Gunakan kode referral ShopeePay SNVQTRYVM saat regis
2. Lengkapi data/upgrade ke ShopeePay Plus https://t.co/1bKgPHWNBn
----------------------------------------

Nomor data: 2
@nnawinss Yukk kak, by req &lt;3 promo 10.10 diskon 10% nih
----------------------------------------

Nomor data: 3
hari terakhir jajan layout promo 10.10 ‼️ lesgoooo. #bealanja
----------------------------------------

Nomor data: 4
@bercyinta Chibi dibawah kak, promo 10.10
----------------------------------------

Nomor data: 5
Masih adakah layout req promo 10.10? Mau jajan req mari #zonauang
----------------------------------------

In [78]:

for _, baris in df_bersih.iloc[5:10].iterrows():
    print(f"\nNomor data: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 40)

Nomor data: 6
@polcadaily Hadireeeu, pas bangeet kak ada promo 10.10 juga :3 intip dibawah yuk
----------------------------------------

Nomor data: 7
[Last day]
Voucher Lazada diskon 15% s/d 1jt
🗓 12 Okt

Klaim semua vouchernya di sini
https://t.co/vtSBIP7Ajm
DAN di sini
https://t.co/4NH9VKnlSW

Promo 10.10
https://t.co/tjTn7lF7r9 https://t.co/f24H7cck7w
----------------------------------------

Nomor data: 8
Kayanya nunggu asapnya sampai Jakarta baru deh jadi Bencana Nasional, mau? Mumpung masih ada promo 10.10
----------------------------------------

Nomor data: 9
LAST DAYYYY. ‼️
siapa yg mau jajan layout promo 10.10 masih bisa yaaa! #bealanja
----------------------------------------

Nomor data: 10
100 ml di aku bisa buat 6-8 bulan karena 1 pump cukup buat semuka. 100k dapet 3 item🤤 ini kemarin promo 10.10 (plis cosrx endorse ak) https://t.co/UIVslPWdBQ
----------------------------------------

In [79]:
for _, baris in df_bersih.iloc[10:15].iterrows():
    print(f"\nNomor data: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 40)

Nomor data: 11
ternyata pas dipake malah keliatan clean, elegan, dan adem banget. Bener-bener susah buat nggak jatuh hati🥹

Cek disini lagi promo 10.10⤵️
🔗 https://t.co/LeddHVEfEO
🔗 https://t.co/LeddHVEfEO
----------------------------------------

Nomor data: 12
https://t.co/MSZzSnarR5

Co online poprs nya silah kan
Lg promo 10.10

#gay #gayjatim #gaymakassar
----------------------------------------

Nomor data: 13
📌Nambang koin Lazada

Tambahan potongan harga
https://t.co/ch4ncAmAaf
(buku, Skincare, produk lain juga banyak)

✅Mumpung masih promo 10.10 https://t.co/30MMPu3tgE
----------------------------------------

Nomor data: 14
@mingih kok lu manja gini si &lt;/333 ????? masa gw hrus beli kalender 2027 skrang juga? promo 10.10 udah lewat ,,
----------------------------------------

Nomor data: 15
Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu. https://t.co/gLL6w3LwJ9
----------------------------------------

In [80]:
for _, baris in df_bersih.iloc[15:20].iterrows():
    print(f"\nNomor data: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 40)

Nomor data: 16
Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu.

Khusus pelanggan baru, promo ini berlaku 10–12 Oktober 2026. https://t.co/R7awStkC7f
----------------------------------------

Nomor data: 17
@manajemenbobrok heeh padahal kamari promo 10.10
----------------------------------------

Nomor data: 18
@kaihkamal @hueningkayih Rame banget sampai saya bingung cara scroll mentab 😥😥. Mau bantu saya? Saya ada promo 10.10 kemarin, tapi kayaknya kamu kehabisan soalnya udah ganti tanggal. Minat promo apa lagi?
----------------------------------------

Nomor data: 19
Yukkk jajang layout chibi dibawah, avail for wabis dan wpp. By req yaaa, ada promo 10.10 disc 10%

#zonauang
----------------------------------------

Nomor data: 20
gas ambil promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/JlRtW95rjx
----------------------------------------

In [81]:
for _, baris in df_bersih.iloc[20:23].iterrows():
    print(f"\nNomor data: {baris['nomor_data']}")
    print(baris["full_text"])
    print("-" * 40)

Nomor data: 21
Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10

❓Tutorial dapetin promo:
1️⃣ Buka website https://t.co/y4qQvqjDx8
2️⃣ Pilih paket belajar yang kamu inginkan
3️⃣ Apply kode promo 10.10
4️⃣ Masukan kode promo PFMMERI

#pahamify #utbk #tka #bimbelonline #agit https://t.co/kQcIA5ukCm
----------------------------------------

Nomor data: 23
Traveloka gelar Promo 10.10, tawarkan diskon tiket di 8 negara  https://t.co/066SxwTmDa
----------------------------------------

Nomor data: 25
hari terakhir promo 10.10

rekomendasi: Live Class &amp; Prime UTBK

cek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN  buat klaim promo

kode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://t.co/9ALgNZVL0U
----------------------------------------

In [82]:

from pathlib import Path
import pandas as pd

# Gunakan 23 teks unik yang sudah diperiksa
df_final = df_bersih.copy()

# Tetapkan kategori relevansi berdasarkan pemeriksaan isi
kategori_relevansi = {
    1: "Promosi digital",
    2: "Tidak relevan: jasa/desain",
    3: "Tidak relevan: jasa/desain",
    4: "Tidak relevan: jasa/desain",
    5: "Tidak relevan: jasa/desain",
    6: "Konteks belum cukup",
    7: "Promosi digital",
    8: "Tidak relevan: konteks tidak berkaitan",
    9: "Tidak relevan: jasa/desain",
    10: "Pengalaman produk saat promo",
    11: "Pengalaman produk saat promo",
    12: "Konteks belum cukup",
    13: "Promosi digital",
    14: "Percakapan: konteks belum cukup",
    15: "Promosi digital",
    16: "Promosi digital",
    17: "Percakapan: konteks belum cukup",
    18: "Promosi digital: konteks terbatas",
    19: "Tidak relevan: jasa/desain",
    20: "Promosi digital",
    21: "Promosi digital",
    23: "Promosi digital",
    25: "Promosi digital"
}

df_final["status_relevansi"] = df_final["nomor_data"].map(
    kategori_relevansi
)

# Simpan hasil tanpa mengubah dataset asli
folder_output = Path("/content/output")
folder_output.mkdir(parents=True, exist_ok=True)

file_final = folder_output / "dataset_promo_1010_final.csv"
df_final.to_csv(file_final, index=False, encoding="utf-8-sig")

print("Jumlah teks unik:", len(df_final))
print("File tersimpan:", file_final)
print("\nRingkasan relevansi:")
display(
    df_final["status_relevansi"]
    .value_counts()
    .rename_axis("status_relevansi")
    .reset_index(name="jumlah")
)

print("\nPratinjau dataset:")
display(
    df_final[
        ["nomor_data", "status_relevansi", "jenis_cuitan",
         "sentimen", "full_text"]
    ]
)

Jumlah teks unik: 23
File tersimpan: /content/output/dataset_promo_1010_final.csv

Ringkasan relevansi:

                         status_relevansi  jumlah
0                         Promosi digital       9
1              Tidak relevan: jasa/desain       6
2                     Konteks belum cukup       2
3            Pengalaman produk saat promo       2
4         Percakapan: konteks belum cukup       2
5  Tidak relevan: konteks tidak berkaitan       1
6       Promosi digital: konteks terbatas       1

Pratinjau dataset:

,nomor_data,status_relevansi,jenis_cuitan,sentimen,full_text
0,1,Promosi digital,Promosi,Netral,"Sewaktu2 suka ada promo 10.10 diskon tagihan listrik &amp; pulsa qris serba seribu di apk ShopeePay. Buat yg baru install, yuk pakai kode referal biar dpt free saldo Rp 5000\n\nCaranya: \n1. Gunakan kode referral ShopeePay SNVQTRYVM saat regis\n2. Lengkapi data/upgrade ke ShopeePay Plus https://..."
1,2,Tidak relevan: jasa/desain,Promosi,Netral,"@nnawinss Yukk kak, by req &lt;3 promo 10.10 diskon 10% nih"
2,3,Tidak relevan: jasa/desain,Lainnya,Tidak cukup konteks,hari terakhir jajan layout promo 10.10 ‼️ lesgoooo. #bealanja
3,4,Tidak relevan: jasa/desain,Lainnya,Tidak cukup konteks,"@bercyinta Chibi dibawah kak, promo 10.10"
4,5,Tidak relevan: jasa/desain,Lainnya,Tidak cukup konteks,Masih adakah layout req promo 10.10? Mau jajan req mari #zonauang
5,6,Konteks belum cukup,Promosi,Netral,"@polcadaily Hadireeeu, pas bangeet kak ada promo 10.10 juga :3 intip dibawah yuk"
6,7,Promosi digital,Promosi,Netral,[Last day]\nVoucher Lazada diskon 15% s/d 1jt\n🗓 12 Okt\n\nKlaim semua vouchernya di sini\nhttps://t.co/vtSBIP7Ajm\nDAN di sini\nhttps://t.co/4NH9VKnlSW\n\nPromo 10.10\nhttps://t.co/tjTn7lF7r9 https://t.co/f24H7cck7w
7,8,Tidak relevan: konteks tidak berkaitan,Lainnya,Tidak cukup konteks,"Kayanya nunggu asapnya sampai Jakarta baru deh jadi Bencana Nasional, mau? Mumpung masih ada promo 10.10"
8,9,Tidak relevan: jasa/desain,Lainnya,Tidak cukup konteks,LAST DAYYYY. ‼️\nsiapa yg mau jajan layout promo 10.10 masih bisa yaaa! #bealanja
9,10,Pengalaman produk saat promo,Konsumen,Positif,100 ml di aku bisa buat 6-8 bulan karena 1 pump cukup buat semuka. 100k dapet 3 item🤤 ini kemarin promo 10.10 (plis cosrx endorse ak) https://t.co/UIVslPWdBQ
10,11,Pengalaman produk saat promo,Konsumen,Positif,"ternyata pas dipake malah keliatan clean, elegan, dan adem banget. Bener-bener susah buat nggak jatuh hati🥹\n\nCek disini lagi promo 10.10⤵️\n🔗 https://t.co/LeddHVEfEO\n🔗 https://t.co/LeddHVEfEO"
11,12,Konteks belum cukup,Lainnya,Tidak cukup konteks,https://t.co/MSZzSnarR5\n\nCo online poprs nya silah kan \nLg promo 10.10\n\n#gay #gayjatim #gaymakassar
12,13,Promosi digital,Promosi,Netral,"📌Nambang koin Lazada\n\nTambahan potongan harga\nhttps://t.co/ch4ncAmAaf\n(buku, Skincare, produk lain juga banyak)\n\n✅Mumpung masih promo 10.10 https://t.co/30MMPu3tgE"
13,14,Percakapan: konteks belum cukup,Percakapan,Negatif,"@mingih kok lu manja gini si &lt;/333 ????? masa gw hrus beli kalender 2027 skrang juga? promo 10.10 udah lewat ,,"
14,15,Promosi digital,Promosi,Netral,"Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu. https://t.co/gLL6w3LwJ9"
15,16,Promosi digital,Promosi,Netral,"Hari terakhir. Promo 10.10, saatnya berlangganan Tempo Plus dengan penawaran terhemat! Nikmati berita premium, laporan investigasi, dan lebih dari 100 kategori berita untuk membantu Anda #LebihPaham berbagai isu.\n\nKhusus pelanggan baru, promo ini berlaku 10–12 Oktober 2026. https://t.co/R7awSt..."
16,17,Percakapan: konteks belum cukup,Percakapan,Tidak cukup konteks,@manajemenbobrok heeh padahal kamari promo 10.10
17,18,Promosi digital: konteks terbatas,Percakapan,Tidak cukup konteks,"@kaihkamal @hueningkayih Rame banget sampai saya bingung cara scroll mentab 😥😥. Mau bantu saya? Saya ada promo 10.10 kemarin, tapi kayaknya kamu kehabisan soalnya udah ganti tanggal. Minat promo apa lagi?"
18,19,Tidak relevan: jasa/desain,Lainnya,Tidak cukup konteks,"Yukkk jajang layout chibi dibawah, avail for wabis dan wpp. By req yaaa, ada promo 10.10 disc 10%\n\n#zonauang"
19,20,Promosi digital,Promosi,Netral,"gas ambil promo 10.10\n\nrekomendasi: Live Class &amp; Prime UTBK\n\ncek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN buat klaim promo\n\nkode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout https://..."
20,21,Promosi digital,Promosi,Netral,Kode Diskon Promo Pahamify 09 - 11 Oktober 2026 : PFMMERI dan 10.10\n\n❓Tutorial dapetin promo:\n1️⃣ Buka website https://t.co/y4qQvqjDx8\n2️⃣ Pilih paket belajar yang kamu inginkan\n3️⃣ Apply kode promo 10.10\n4️⃣ Masukan kode promo PFMMERI\n\n#pahamify #utbk #tka #bimbelonline #agit https://t....
22,23,Promosi digital,Promosi,Netral,"Traveloka gelar Promo 10.10, tawarkan diskon tiket di 8 negara https://t.co/066SxwTmDa"
24,25,Promosi digital,Promosi,Netral,"hari terakhir promo 10.10\n\nrekomendasi: Live Class &amp; Prime UTBK\n\ncek &amp; beli di web yang ada di poster, masukan kode PFMSIAPTOPTN buat klaim promo\n\nkode diskon pahamify mipy bimbel online UTBK SNBT TKA simak ui ujian mandiri ugm itb unpad its ipb um Undip belajar online Tryout http..."

In [83]:

from pathlib import Path

file_final = Path("/content/output/dataset_promo_1010_final.csv")
file_final.parent.mkdir(parents=True, exist_ok=True)

df_final.to_csv(file_final, index=False, encoding="utf-8-sig")

print("File berhasil disimpan!")
print("Lokasi:", file_final)
print("Jumlah baris:", len(df_final))
print("Jumlah kolom:", len(df_final.columns))
print("\nNama kolom:")
print(df_final.columns.tolist())

File berhasil disimpan!
Lokasi: /content/output/dataset_promo_1010_final.csv
Jumlah baris: 23
Jumlah kolom: 21

Nama kolom:
['nomor_data', 'conversation_id_str', 'created_at', 'favorite_count', 'full_text', 'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location', 'quote_count', 'reply_count', 'retweet_count', 'tweet_url', 'user_id_str', 'username', 'jenis_cuitan', 'sentimen', 'alasan_label', 'teks_normalisasi', 'status_relevansi']

In [84]:

from google.colab import files

files.download("/content/output/dataset_promo_1010_final.csv")